use super::SignatureHit;
use std::collections::BTreeMap;

fn module_ident(module: &str) -> String {
    module.trim_end_matches(".dll").replace('.', "_")
}

/// Generate offsets.hpp with resolved RIPREL addresses
pub fn render_offsets_hpp(hits: &[SignatureHit]) -> String {
    let mut s = String::new();
    s.push_str("// Auto-generated by cs2-sdk. Do not edit.\n");
    s.push_str("// Global variable offsets resolved from signatures.\n");
    s.push_str("#pragma once\n\n#include <cstdint>\n\n");
    
    // Group by module
    let mut by_module: BTreeMap<&str, Vec<&SignatureHit>> = BTreeMap::new();
    for h in hits.iter().filter(|h| h.found && h.resolve == "riprel") {
        by_module.entry(h.module.as_str()).or_default().push(h);
    }
    
    s.push_str("namespace cs2::offsets {\n");
    for (module, items) in by_module {
        s.push_str(&format!("    namespace {} {{\n", module_ident(module)));
        for h in items {
            if let Some(rva) = h.rva {
                s.push_str(&format!(
                    "        constexpr uintptr_t {} = 0x{:X};\n",
                    h.name, rva
                ));
            }
        }
        s.push_str("    }\n");
    }
    s.push_str("}\n");
    
    s
}
