// Auto-generated by cs2-universal-dumper. Do not edit.

namespace CS2Sdk.Signatures;

public static class Signatures
{
    public static class animationsystem
    {
        public const ulong Animation__ShouldUpdateSequences = 0x7FFAED6EF0A0UL; // rva 0x14F0A0
        public const ulong AnimationSystemUtils_ptr = 0x7FFAEDDB2170UL; // rva 0x812170
    }
    public static class client
    {
        public const ulong AddNametagEntity = 0x7FFABF4FB070UL; // rva 0x78B070
        public const ulong AddStattrakEntity = 0x7FFABF7BC790UL; // rva 0xA4C790
        public const ulong AnimGraphRebuild = 0x7FFABF61EC70UL; // rva 0x8AEC70
        public const ulong ApplyEconCustomization = 0x7FFABF518A90UL; // rva 0x7A8A90
        public const ulong AutowallInit = 0x7FFABF651EE0UL; // rva 0x8E1EE0
        public const ulong AutowallTraceData = 0x7FFABF6FE9C0UL; // rva 0x98E9C0
        public const ulong AutowallTracePos = 0x7FFABF577780UL; // rva 0x807780
        public const ulong BulkRegenIterator = 0x7FFABF4FE571UL; // rva 0x78E571
        public const ulong CAM_ThinkReturn = 0x7FFABF08A4FFUL; // rva 0x31A4FF
        public const ulong CAttributeStringFill = 0x7FFABFC1EC20UL; // rva 0xEAEC20
        public const ulong CAttributeStringInit = 0x7FFABF3686B0UL; // rva 0x5F86B0
        public const ulong CBaseEntity_ChangeModel = 0x7FFABF64B1C0UL; // rva 0x8DB1C0
        public const ulong CBaseEntity_TakeDamageOld = 0x7FFABEF93D20UL; // rva 0x223D20
        public const ulong CBaseModelEntity_SetBodygroup = 0x7FFABF649E70UL; // rva 0x8D9E70
        public const ulong CBodyComponent = 0x7FFABEF2C160UL; // rva 0x1BC160
        public const ulong CBodyComponentSkeletonInstance = 0x7FFABEF33040UL; // rva 0x1C3040
        public const ulong CBufferStringInit = 0x7FFAC05529D0UL; // rva 0x17E29D0
        public const ulong CCSGOInput__CreateMove = 0x7FFABF9CE7F0UL; // rva 0xC5E7F0
        public const ulong CCSGameRules = 0x7FFABEDEE160UL; // rva 0x7E160
        public const ulong CCSGameRulesProxy = 0x7FFABF459500UL; // rva 0x6E9500
        public const ulong CCSPlayerController = 0x7FFABF555220UL; // rva 0x7E5220
        public const ulong CCSPlayerController = 0x7FFABF555220UL; // rva 0x7E5220
        public const ulong CCSPlayerController_ActionTrackingServices = 0x7FFABF555220UL; // rva 0x7E5220
        public const ulong CCSPlayerController_DamageServices = 0x7FFABF555220UL; // rva 0x7E5220
        public const ulong CCSPlayerController_InGameMoneyServices = 0x7FFABF555220UL; // rva 0x7E5220
        public const ulong CCSPlayerController_InventoryServices = 0x7FFABF555220UL; // rva 0x7E5220
        public const ulong CCSPlayerInventory__GetItemInLoadout = 0x7FFABF533D70UL; // rva 0x7C3D70
        public const ulong CCSPlayerPawn = 0x7FFABF920E40UL; // rva 0xBB0E40
        public const ulong CCSPlayer_BulletServices = 0x7FFABF583BA0UL; // rva 0x813BA0
        public const ulong CCSPlayer_BulletServices = 0x7FFABF583BA0UL; // rva 0x813BA0
        public const ulong CCSPlayer_CameraServices = 0x7FFABF57FCB0UL; // rva 0x80FCB0
        public const ulong CCSPlayer_HostageServices = 0x7FFABF583BA0UL; // rva 0x813BA0
        public const ulong CCSPlayer_ItemServices = 0x7FFABF5C0B00UL; // rva 0x850B00
        public const ulong CCSPlayer_MovementServices = 0x7FFABF5ADE80UL; // rva 0x83DE80
        public const ulong CCSPlayer_MovementServices = 0x7FFABF5ADE80UL; // rva 0x83DE80
        public const ulong CCSPlayer_PingServices = 0x7FFABF5C0ED0UL; // rva 0x850ED0
        public const ulong CCSPlayer_RunCommand_Context = 0x7FFABF74BAF0UL; // rva 0x9DBAF0
        public const ulong CCSPlayer_UseServices = 0x7FFABF5F21D0UL; // rva 0x8821D0
        public const ulong CCSPlayer_WaterServices = 0x7FFABF5E7460UL; // rva 0x877460
        public const ulong CCSPlayer_WeaponServices = 0x7FFABF5E7810UL; // rva 0x877810
        public const ulong CCSPlayer_WeaponServices = 0x7FFABF5E7810UL; // rva 0x877810
        public const ulong CCSWeaponBase = 0x7FFABF4EF3D0UL; // rva 0x77F3D0
        public const ulong CCSWeaponBaseGun = 0x7FFABF4EF470UL; // rva 0x77F470
        public const ulong CCSWeaponBaseVData = 0x7FFABF4CA2B0UL; // rva 0x75A2B0
        public const ulong CCollisionProperty = 0x7FFABF050F90UL; // rva 0x2E0F90
        public const ulong CCompositeMaterialManager_AddPanoramaPanelRenderRequest_Caller = 0x7FFAC012B8D4UL; // rva 0x13BB8D4
        public const ulong CDecoyProjectile = 0x7FFABF4BE1E0UL; // rva 0x74E1E0
        public const ulong CEconItemSchema__GetAttributeDefinitionByName = 0x7FFABFDBCEA0UL; // rva 0x104CEA0
        public const ulong CEconItemView__GetCustomPaintKitIndex = 0x7FFABFE18A60UL; // rva 0x10A8A60
        public const ulong CFlashbangProjectile = 0x7FFABFD503F0UL; // rva 0xFE03F0
        public const ulong CFogController = 0x7FFABEFEEFD0UL; // rva 0x27EFD0
        public const ulong CGameSceneNode = 0x7FFABEF138F0UL; // rva 0x1A38F0
        public const ulong CGameSceneNode_BuildBoneMergeWork = 0x7FFABF6AFA40UL; // rva 0x93FA40
        public const ulong CGameSceneNode_StartHierarchicalAttachment = 0x7FFABF6FC5E0UL; // rva 0x98C5E0
        public const ulong CGameTrace_TraceShape_Client = 0x7FFABF6FEAA0UL; // rva 0x98EAA0
        public const ulong CGlowProperty = 0x7FFABF0511A0UL; // rva 0x2E11A0
        public const ulong CGlowProperty_OnGlowTypeChanged = 0x7FFABF87CD90UL; // rva 0xB0CD90
        public const ulong CHEGrenadeProjectile = 0x7FFABFD50490UL; // rva 0xFE0490
        public const ulong CInputPtrGlobal = 0x7FFAC0DD4330UL; // rva 0x2064330
        public const ulong CMolotovProjectile = 0x7FFABF4BE3C0UL; // rva 0x74E3C0
        public const ulong CPaintKitDefinitions_FindOrCreateByName = 0x7FFABFDCA690UL; // rva 0x105A690
        public const ulong CPaintKitDefinitions_LoadDefaultKit = 0x7FFABFD9C760UL; // rva 0x102C760
        public const ulong CPostProcessingVolume = 0x7FFABF013D60UL; // rva 0x2A3D60
        public const ulong CS2ItemEditor_BuildTemplateMaterialFromFile = 0x7FFAC012CA50UL; // rva 0x13BCA50
        public const ulong CSBaseGunFireData_fn = 0x7FFAC0258140UL; // rva 0x14E8140
        public const ulong CSGOInput_ptr = 0x7FFAC0DD4330UL; // rva 0x2064330
        public const ulong CSGOInput_resolved = 0x7FFAC0DD4337UL; // rva 0x2064337
        public const ulong CSkeletonInstance = 0x7FFABEF13A20UL; // rva 0x1A3A20
        public const ulong CSkeletonInstance__SetMeshGroupMask = 0x7FFABF79DB50UL; // rva 0xA2DB50
        public const ulong CSkeletonInstance_GetTransformsForHitboxList = 0x7FFABF78A6C0UL; // rva 0xA1A6C0
        public const ulong CSkeletonInstance_OnBodyGroupChoiceChanged = 0x7FFABF795310UL; // rva 0xA25310
        public const ulong CSkeletonInstance_PostDataUpdate = 0x7FFABF7964B0UL; // rva 0xA264B0
        public const ulong CSkeletonInstance_SetMaterialGroup = 0x7FFABF79C830UL; // rva 0xA2C830
        public const ulong CSkeletonInstance_SetMeshGroupMask = 0x7FFABF795480UL; // rva 0xA25480
        public const ulong CSmokeGrenadeProjectile = 0x7FFABF4BE460UL; // rva 0x74E460
        public const ulong CTonemapController2 = 0x7FFABEFC7C90UL; // rva 0x257C90
        public const ulong CUtlVector_CompositeMaterialInput_AddToTail = 0x7FFABF4F9C50UL; // rva 0x789CA2
        public const ulong C_AttributeContainer = 0x7FFABF988BB0UL; // rva 0xC18BB0
        public const ulong C_BaseEntity = 0x7FFABEDBE260UL; // rva 0x4E260
        public const ulong C_BaseModelEntity = 0x7FFABEEC8010UL; // rva 0x158010
        public const ulong C_BasePlayerPawn = 0x7FFABEDDDA20UL; // rva 0x6DA20
        public const ulong C_C4 = 0x7FFABEE0A420UL; // rva 0x9A420
        public const ulong C_CSPlayerPawn = 0x7FFABF432430UL; // rva 0x6C2430
        public const ulong C_CSPlayerPawnBase = 0x7FFABF947140UL; // rva 0xBD7140
        public const ulong C_CSWeaponBase = 0x7FFABF4B2170UL; // rva 0x742170
        public const ulong C_EconEntity_BuildLegacyGloveSkinMaterial = 0x7FFABF931460UL; // rva 0xBC1460
        public const ulong C_EconEntity_BuildLegacyWeaponSkinMaterial = 0x7FFABF4FC2A0UL; // rva 0x78C2A0
        public const ulong C_EconEntity_BuildModernWeaponSkinMaterial = 0x7FFABFAF4F90UL; // rva 0xD84F90
        public const ulong C_EconEntity_BuildNametagOverlayMaterial = 0x7FFABF4FB070UL; // rva 0x78B070
        public const ulong C_EconItemView = 0x7FFABF47B570UL; // rva 0x70B570
        public const ulong C_EconWearable_OnNewCustomMaterials = 0x7FFABFE29090UL; // rva 0x10B9090
        public const ulong C_Hostage = 0x7FFABEE57480UL; // rva 0xE7480
        public const ulong C_Inferno = 0x7FFABEE67440UL; // rva 0xF7440
        public const ulong C_PlantedC4 = 0x7FFABEE607A0UL; // rva 0xF07A0
        public const ulong C_SmokeGrenadeProjectile = 0x7FFABEE05A10UL; // rva 0x95A10
        public const ulong CacheParticleEffect = 0x7FFABEF77BC0UL; // rva 0x207BC0
        public const ulong CalcSpread = 0x7FFABF9EEBF0UL; // rva 0xC7EBF0
        public const ulong CalcViewmodelTransform_v2 = 0x7FFABF5124F0UL; // rva 0x7A24F0
        public const ulong CalcViewmodelView = 0x7FFABF9DBF20UL; // rva 0xC6BF20
        public const ulong CalculateInterpolation = 0x7FFAC0237E70UL; // rva 0x14C7E70
        public const ulong ClearHUDWeaponIcon = 0x7FFABFB5DDD0UL; // rva 0xDEDDD0
        public const ulong ClientModeCSNormal_OnEvent = 0x7FFABF9CC660UL; // rva 0xC5C660
        public const ulong ClientMode_ptr = 0x7FFAC10AEAE0UL; // rva 0x233EAE0
        public const ulong Client_DispatchSpawn = 0x7FFAC0245B10UL; // rva 0x14D5B10
        public const ulong CompositeMaterialPanoramaPanel_Init = 0x7FFABF901260UL; // rva 0xB91260
        public const ulong ComputeRandomSeed = 0x7FFABF9EE2D0UL; // rva 0xC7E2D0
        public const ulong ConCommand_firstperson = 0x7FFABF83A2B0UL; // rva 0xACA2B0
        public const ulong ConCommand_thirdperson = 0x7FFABF83A390UL; // rva 0xACA390
        public const ulong ConvarGet = 0x7FFABF62F602UL; // rva 0x8BF602
        public const ulong CreateBaseTypeCache = 0x7FFAC0280EA0UL; // rva 0x1510EA0
        public const ulong CreateEntityByClassName = 0x7FFAC0374C46UL; // rva 0x1604C46
        public const ulong CreateInterface = 0x7FFAC05A5790UL; // rva 0x1835790
        public const ulong CreateNewSubtickMoveStep = 0x7FFABF221D80UL; // rva 0x4B1D80
        public const ulong CreateParticleEffect = 0x7FFABF6F7020UL; // rva 0x987020
        public const ulong CreateSOSubclassEconItem = 0x7FFABFD67770UL; // rva 0xFF7770
        public const ulong DamageFeedbackEmitter = 0x7FFABF58FB40UL; // rva 0x81FB40
        public const ulong DestroyParticle = 0x7FFABF6B63E0UL; // rva 0x9463E0
        public const ulong DispatchEffect = 0x7FFABF0CA570UL; // rva 0x35A570
        public const ulong DispatchSpawn_caller = 0x7FFAC0245B10UL; // rva 0x14D5B10
        public const ulong DrawLegs = 0x7FFABFE60410UL; // rva 0x10F0410
        public const ulong DrawOverHead = 0x7FFABF7D6CF0UL; // rva 0xA66CF0
        public const ulong DrawSmokeVertex = 0x7FFABF9EB290UL; // rva 0xC7B290
        public const ulong EmitSoundByHandle = 0x7FFABF8D3B10UL; // rva 0xB63B10
        public const ulong FX_FireBullets = 0x7FFABF9EE380UL; // rva 0xC7E380
        public const ulong FX_FireBullets = 0x7FFABF9EE380UL; // rva 0xC7E380
        public const ulong FindHudElement = 0x7FFABFB31E98UL; // rva 0xDC1E98
        public const ulong FindHudElement_panorama = 0x7FFABFB33E70UL; // rva 0xDC3E70
        public const ulong FindSOCache = 0x7FFAC058F080UL; // rva 0x181F080
        public const ulong FirstPersonLegs = 0x7FFABFE60410UL; // rva 0x10F0410
        public const ulong FlashOverlay = 0x7FFABFB1B2C0UL; // rva 0xDAB2C0
        public const ulong ForceButtonsDown = 0x7FFABF740130UL; // rva 0x9D0130
        public const ulong GameEntitySystemPtr = 0x7FFAC1241DF0UL; // rva 0x24D1DF0
        public const ulong GameEventManager_AddListener = 0x7FFABF6A9FF0UL; // rva 0x939FF0
        public const ulong GameEventManager_UnserializeEvent = 0x7FFABF702900UL; // rva 0x992900
        public const ulong GameRules_ptr = 0x7FFAC109BFB8UL; // rva 0x232BFB8
        public const ulong GetBBox_ptr = 0x7FFAC109BFB8UL; // rva 0x232BFB8
        public const ulong GetBaseEntity = 0x7FFABF6D7600UL; // rva 0x967600
        public const ulong GetBonePositionByName = 0x7FFABF6381E0UL; // rva 0x8C81E0
        public const ulong GetChatObject = 0x7FFABFE33670UL; // rva 0x10C3670
        public const ulong GetClientSystem = 0x7FFABFDA6570UL; // rva 0x1036570
        public const ulong GetControllerCmd = 0x7FFABF62DC00UL; // rva 0x8BDC00
        public const ulong GetEconItemSystem = 0x7FFABF0E9830UL; // rva 0x379830
        public const ulong GetEntityByIndex = 0x7FFABF6D7600UL; // rva 0x967600
        public const ulong GetEntityHandle = 0x7FFABF6BE8D0UL; // rva 0x94E8D0
        public const ulong GetGlowColor = 0x7FFABF87ABC0UL; // rva 0xB0ABC0
        public const ulong GetHitGroup = 0x7FFABF787C40UL; // rva 0xA17C40
        public const ulong GetInstanceS = 0x7FFAC102A670UL; // rva 0x22BA670
        public const ulong GetInt2_Event = 0x7FFABF21AB40UL; // rva 0x4AAB40
        public const ulong GetInventoryManager = 0x7FFABF536430UL; // rva 0x7C6430
        public const ulong GetLocalControllerById = 0x7FFABF651070UL; // rva 0x8E1070
        public const ulong GetLocalPawn = 0x7FFABF651070UL; // rva 0x8E1070
        public const ulong GetLocalPlayer_dispatcher = 0x7FFABF0E9200UL; // rva 0x379200
        public const ulong GetMatrixForView = 0x7FFABEED9C50UL; // rva 0x169C50
        public const ulong GetPlayerByIndex_export = 0x7FFABFC70910UL; // rva 0xF00910
        public const ulong GetPlayerInterp = 0x7FFABF629460UL; // rva 0x8B9460
        public const ulong GetRemovedAimPunch_E8 = 0x7FFABF5BD6E0UL; // rva 0x84D6E0
        public const ulong GetRemovedAimpunch = 0x7FFABEE82947UL; // rva 0x112947
        public const ulong GetSurfaceData = 0x7FFABF6C3540UL; // rva 0x953540
        public const ulong GetTickBase = 0x7FFABF62DA00UL; // rva 0x8BDA00
        public const ulong GetTraceInfo = 0x7FFABF576F50UL; // rva 0x806F50
        public const ulong GetUserCmdManager = 0x7FFABF62DC90UL; // rva 0x8BDC90
        public const ulong GetViewAngles = 0x7FFABF845CA0UL; // rva 0xAD5CA0
        public const ulong GetWeaponInAccuracyRecoveryTime = 0x7FFABF506600UL; // rva 0x796600
        public const ulong GetWorldFovResolver = 0x7FFABF57CEF0UL; // rva 0x80CEF0
        public const ulong GlobalLightUpdateState = 0x7FFABF7FB5A0UL; // rva 0xA8B5A0
        public const ulong GlobalVariables_ptr = 0x7FFAC0DBC5D8UL; // rva 0x204C5D8
        public const ulong GloveApply_PerTick = 0x7FFABF931460UL; // rva 0xBC1460
        public const ulong GlowManager_ptr = 0x7FFAC1098DB0UL; // rva 0x2328DB0
        public const ulong GlowObjectManager_GetInstance = 0x7FFABF87ACD0UL; // rva 0xB0ACD0
        public const ulong HandleBulletPenetration = 0x7FFABF5911F0UL; // rva 0x8211F0
        public const ulong HandleEntityList = 0x7FFABEF33700UL; // rva 0x1C3700
        public const ulong HandleTeamIntro = 0x7FFABF473EB0UL; // rva 0x703EB0
        public const ulong HudChatPrintf = 0x7FFABFE310F0UL; // rva 0x10C10F0
        public const ulong InfoForResourceTypeCCompositeMaterialKit_TypeManager = 0x7FFAC01490B0UL; // rva 0x13D90B0
        public const ulong InfoForResourceTypeCCompositeMaterial_TypeManager = 0x7FFAC0149600UL; // rva 0x13D9600
        public const ulong InitFilter = 0x7FFABF09BBF0UL; // rva 0x32BBF0
        public const ulong InitPlayerMovementTraceFilter = 0x7FFABF5B0660UL; // rva 0x840660
        public const ulong InitTraceInfo = 0x7FFAC036C2A0UL; // rva 0x15FC2A0
        public const ulong IsGlowing = 0x7FFABF87C300UL; // rva 0xB0C300
        public const ulong KillFeedbackEmitter = 0x7FFABF5BB0F0UL; // rva 0x84B0F0
        public const ulong LevelInit = 0x7FFABF640100UL; // rva 0x8D0100
        public const ulong LoadFileForMe = 0x7FFABF68BF40UL; // rva 0x91BF40
        public const ulong LoadPath = 0x7FFABF42B200UL; // rva 0x6BB200
        public const ulong LocalPlayerController_ptr = 0x7FFAC107B5D0UL; // rva 0x230B5D0
        public const ulong LookupBone = 0x7FFABF6381E0UL; // rva 0x8C81E0
        public const ulong ModulationUpdate = 0x7FFABF74A450UL; // rva 0x9DA450
        public const ulong NoClipOnChange = 0x7FFABEED6C00UL; // rva 0x166C00
        public const ulong NoSpread1 = 0x7FFABF9EE2D0UL; // rva 0xC7E2D0
        public const ulong ParticleCollection = 0x7FFABEF64D90UL; // rva 0x1F4D90
        public const ulong ParticleManager_ptr = 0x7FFAC0DA09E8UL; // rva 0x20309E8
        public const ulong PhysicsRunThink_Ctrl = 0x7FFABF647310UL; // rva 0x8D7310
        public const ulong PhysicsRunThink_Pawn = 0x7FFABF87ED50UL; // rva 0xB0ED50
        public const ulong PlayVSound_client = 0x7FFAC027ED00UL; // rva 0x150ED00
        public const ulong Prediction_ptr = 0x7FFAC0DC7630UL; // rva 0x2057630
        public const ulong ProcessImpacts = 0x7FFABF73EA50UL; // rva 0x9CEA50
        public const ulong ProcessMovement = 0x7FFABF749A30UL; // rva 0x9D9A30
        public const ulong RegenerateWeaponSkin = 0x7FFABF4FC2A0UL; // rva 0x78C2A0
        public const ulong RegenerateWeaponSkin_v2 = 0x7FFABF4FC2A0UL; // rva 0x78C2A0
        public const ulong RegenerateWeaponSkins = 0x7FFABF520D40UL; // rva 0x7B0D40
        public const ulong RenderDecals = 0x7FFABFE5CA50UL; // rva 0x10ECA50
        public const ulong ReportHit = 0x7FFABF372290UL; // rva 0x602290
        public const ulong RunCommand = 0x7FFABF74BAF0UL; // rva 0x9DBAF0
        public const ulong RunCommand_processor = 0x7FFABF74BAF0UL; // rva 0x9DBAF0
        public const ulong Scope_callsite = 0x7FFABF5CD530UL; // rva 0x85D530
        public const ulong SendChatMessage = 0x7FFABFE310F0UL; // rva 0x10C10F0
        public const ulong Sensitivity_ptr = 0x7FFAC10998C0UL; // rva 0x23298C0
        public const ulong SetAbsOrigin_Pawn = 0x7FFABEF8EF50UL; // rva 0x21EF50
        public const ulong SetBodyGroup_inv = 0x7FFABFB072A0UL; // rva 0xD972A0
        public const ulong SetCollisionBounds = 0x7FFABF573980UL; // rva 0x803980
        public const ulong SetDynamicAttributeValue = 0x7FFABFD74F60UL; // rva 0x1004F60
        public const ulong SetDynamicAttributeValue_raw = 0x7FFABFD74F60UL; // rva 0x1004F60
        public const ulong SetMeshGroupMask = 0x7FFABF79DB50UL; // rva 0xA2DB50
        public const ulong SetModel = 0x7FFABF64B1C0UL; // rva 0x8DB1C0
        public const ulong SetPlayerReady = 0x7FFABFC8DD90UL; // rva 0xF1DD90
        public const ulong SetPlayerReady = 0x7FFABFC8DD90UL; // rva 0xF1DD90
        public const ulong SetTraceData = 0x7FFABF544810UL; // rva 0x7D4810
        public const ulong SetTypeKV3 = 0x7FFAC058AEB0UL; // rva 0x181AEB0
        public const ulong SetViewAngle = 0x7FFABF854CE0UL; // rva 0xAE4CE0
        public const ulong SetupCmd = 0x7FFABF62AF20UL; // rva 0x8BAF20
        public const ulong SetupMove = 0x7FFABFA8D0E0UL; // rva 0xD1D0E0
        public const ulong SetupMovementMoves = 0x7FFABFEF6C8FUL; // rva 0x1186C8F
        public const ulong ShowMessageBox = 0x7FFABFA153B0UL; // rva 0xCA53B0
        public const ulong SomeTimingFromPawn = 0x7FFABF7C72B0UL; // rva 0xA572B0
        public const ulong Spawner_PerTickOrchestrator = 0x7FFABF933FE0UL; // rva 0xBC3FE0
        public const ulong SpectatorInput = 0x7FFABF5492E0UL; // rva 0x7D92E0
        public const ulong SpreadSeedGen = 0x7FFABF9EE2D0UL; // rva 0xC7E2D0
        public const ulong TestSurfaces = 0x7FFABF576E30UL; // rva 0x806E30
        public const ulong ThirdPersonOffHandler = 0x7FFABF83A2B0UL; // rva 0xACA2B0
        public const ulong ThirdPersonOnHandler = 0x7FFABF83A390UL; // rva 0xACA390
        public const ulong TraceCreate = 0x7FFABF574900UL; // rva 0x804900
        public const ulong TraceGetInfo = 0x7FFABF576F50UL; // rva 0x806F50
        public const ulong TraceHandleBulletPen = 0x7FFABF5911F0UL; // rva 0x8211F0
        public const ulong TraceInitData = 0x7FFABF570580UL; // rva 0x800580
        public const ulong TraceInitFilter = 0x7FFABF09BBF0UL; // rva 0x32BBF0
        public const ulong TraceInitInfo = 0x7FFAC036C2A0UL; // rva 0x15FC2A0
        public const ulong TracePlayerBBox = 0x7FFABF8E0E30UL; // rva 0xB70E30
        public const ulong TraceShape = 0x7FFABF6FEAA0UL; // rva 0x98EAA0
        public const ulong TraceShape_Client = 0x7FFABF6FEAA0UL; // rva 0x98EAA0
        public const ulong TraceToExit = 0x7FFABF574900UL; // rva 0x804900
        public const ulong UpdateGlobalVars = 0x7FFABF854730UL; // rva 0xAE4730
        public const ulong UpdatePostProcessing = 0x7FFABFC91F20UL; // rva 0xF21F20
        public const ulong UpdatePostProcessing = 0x7FFABFC91F20UL; // rva 0xF21F20
        public const ulong UpdateSkybox = 0x7FFABEFCA850UL; // rva 0x25A850
        public const ulong UpdateSubClass = 0x7FFABEF6A93BUL; // rva 0x1FA93B
        public const ulong UpdateTurningInAccuracy = 0x7FFABF51FDA0UL; // rva 0x7AFDA0
        public const ulong VPhys2World_ptr = 0x7FFAC0DA06C8UL; // rva 0x20306C8
        public const ulong ViewModelHideZoomed = 0x7FFABF510460UL; // rva 0x7A0460
        public const ulong ViewRender_ptr = 0x7FFAC10A0D38UL; // rva 0x2330D38
        public const ulong WeaponC4_ptr = 0x7FFAC1019D58UL; // rva 0x22A9D58
        public const ulong WriteSubtickFromEntry = 0x7FFABF9C6330UL; // rva 0xC56330
        public const ulong draw_smoke_array = 0x7FFABF9EB380UL; // rva 0xC7B380
        public const ulong draw_view_punch_v2 = 0x7FFABF5741C0UL; // rva 0x8041C0
        public const ulong entity_list_ptr = 0x7FFAC1241EF8UL; // rva 0x24D1EF8
        public const ulong frame_stage_notify = 0x7FFABF842D31UL; // rva 0xAD2D31
        public const ulong get_fov = 0x7FFABF5741C0UL; // rva 0x8041C0
        public const ulong get_map_name = 0x7FFABFC4D4F0UL; // rva 0xEDD4F0
        public const ulong get_view_angles_v2 = 0x7FFABF844600UL; // rva 0xAD4600
        public const ulong global_vars_v2 = 0x7FFAC109BFB8UL; // rva 0x232BFB8
        public const ulong is_demo_or_hltv = 0x7FFABFC6E9B0UL; // rva 0xEFE9B0
        public const ulong level_init_v2 = 0x7FFABF86A990UL; // rva 0xAFA990
        public const ulong level_shutdown = 0x7FFABF86AC10UL; // rva 0xAFAC10
        public const ulong local_controller = 0x7FFAC107B5D0UL; // rva 0x230B5D0
        public const ulong mark_interp_latch_flags_dirty = 0x7FFABEF88070UL; // rva 0x218070
        public const ulong on_add_entity_v2 = 0x7FFABF6D8BB0UL; // rva 0x968BB0
        public const ulong override_view_short = 0x7FFABF9CF840UL; // rva 0xC5F840
        public const ulong paintkit_prefab = 0x7FFABFDCD3B0UL; // rva 0x105D3B0
        public const ulong paintkit_seed = 0x7FFABFC61330UL; // rva 0xEF1330
        public const ulong paintkit_wear = 0x7FFABFC61330UL; // rva 0xEF1330
        public const ulong planted_c4_ptr = 0x7FFAC1019D58UL; // rva 0x22A9D58
        public const ulong remove_legs = 0x7FFABFE60410UL; // rva 0x10F0410
        public const ulong statTrak_killEater = 0x7FFABFC61330UL; // rva 0xEF1330
        public const ulong statTrak_scoreType = 0x7FFABEE8B7F0UL; // rva 0x11B7F0
        public const ulong update_global_vars = 0x7FFABF854730UL; // rva 0xAE4730
        public const ulong update_post_processing_v2 = 0x7FFABFC964D6UL; // rva 0xF264D6
        public const ulong view_matrix_ptr = 0x7FFAC10A1B30UL; // rva 0x2331B30
    }
    public static class engine2
    {
        public const ulong BuildNumber_addr = 0x7FFB13CDCC74UL; // rva 0x60CC74
        public const ulong CCommand_Tokenize = 0x7FFB13ACD710UL; // rva 0x3FD710
        public const ulong CGameClient_ClientCommand = 0x7FFB13771240UL; // rva 0xA1240
        public const ulong CHLTVClient_ExecuteStringCommand = 0x7FFB137F0D70UL; // rva 0x120D70
        public const ulong CSplitScreenSlot = 0x7FFB1391A250UL; // rva 0x24A250
        public const ulong Cvar_RegisterConCommand = 0x7FFB13ACD270UL; // rva 0x3FD270
        public const ulong Cvar_RegisterConVar = 0x7FFB13ACC080UL; // rva 0x3FC080
        public const ulong DisablePvsAccessor = 0x7FFB1390D3D2UL; // rva 0x23D3D2
        public const ulong Engine__GetScreenAspectRatio = 0x7FFB137469D0UL; // rva 0x769D0
        public const ulong Engine__PVSManager_ptr = 0x7FFB13CE33F0UL; // rva 0x6133F0
        public const ulong Engine__RunPrediction = 0x7FFB13736490UL; // rva 0x66490
        public const ulong Engine_Disconnect_main = 0x7FFB138A1510UL; // rva 0x1D1510
        public const ulong Engine_HLTVClient_ExecuteStringCommand = 0x7FFB137F0D70UL; // rva 0x120D70
        public const ulong Engine_HostStateMgr_QueueNewRequest = 0x7FFB138EAFC0UL; // rva 0x21AFC0
        public const ulong Engine_HostStateMgr_QueueNewRequest = 0x7FFB138EAFC0UL; // rva 0x21AFC0
        public const ulong Engine_LoadGameInfo = 0x7FFB1385D760UL; // rva 0x18D760
        public const ulong Engine_MountAddon = 0x7FFB13863440UL; // rva 0x193440
        public const ulong Engine_NetTimeoutDisconnect = 0x7FFB13739780UL; // rva 0x69780
        public const ulong Engine_NetworkGameClient_Connect = 0x7FFB1374F400UL; // rva 0x7F400
        public const ulong Engine_NetworkGameClient_SetSignonState = 0x7FFB13730F80UL; // rva 0x60F80
        public const ulong Engine_RegisterConCommand = 0x7FFB13ACD270UL; // rva 0x3FD270
        public const ulong Engine_RegisterConVar = 0x7FFB13ACC080UL; // rva 0x3FC080
        public const ulong IsInGame = 0x7FFB13746450UL; // rva 0x76450
        public const ulong NetworkGameClient_ptr = 0x7FFB13FDA0C0UL; // rva 0x90A0C0
        public const ulong WindowHeight_addr = 0x7FFB13FDE4ECUL; // rva 0x90E4EC
        public const ulong WindowWidth_addr = 0x7FFB13FDE4E8UL; // rva 0x90E4E8
    }
    public static class filesystem_stdio
    {
        public const ulong FullFileSystem_ptr = 0x7FFB136B57A0UL; // rva 0x2157A0
    }
    public static class inputsystem
    {
        public const ulong InputSystemSvc_ptr = 0x7FFB2B7F2B50UL; // rva 0x42B50
        public const ulong InputSystem_ptr = 0x7FFB2B7F2B50UL; // rva 0x42B50
    }
    public static class matchmaking
    {
        public const ulong GameTypes_ptr = 0x7FFABD560F80UL; // rva 0x1B0F80
    }
    public static class materialsystem2
    {
        public const ulong CMaterial2_CompileComboAndGetVariables_DynamicShaderCompile = 0x7FFB11253FA0UL; // rva 0x13FA0
        public const ulong CMaterial2_GetMode = 0x7FFB1124BD40UL; // rva 0xBD40
        public const ulong CMaterial2_GetVertexShaderInputSignature = 0x7FFB1124C8C0UL; // rva 0xC8C0
        public const ulong CMaterial2_GetVertexShaderInputSignature = 0x7FFB1124C8C0UL; // rva 0xC8C0
        public const ulong CMaterial2_LoadShadersAndSetupModes = 0x7FFB11250040UL; // rva 0x10040
        public const ulong CMaterialLayer_ApplyMaterialVarsForBatch = 0x7FFB11258B80UL; // rva 0x18B80
        public const ulong CMaterialLayer_BuildPassCommandData = 0x7FFB11258F80UL; // rva 0x18F80
        public const ulong CMaterialLayer_ComputeWorkItemsToSetupStaticCombosForMode = 0x7FFB11255F3CUL; // rva 0x15F3C
        public const ulong CMaterialLayer_CreateCommandBuffer = 0x7FFB11259820UL; // rva 0x19820
        public const ulong CMaterialSystem2_BindIdentityInstanceIDBufferAndSetRenderState = 0x7FFB112B0000UL; // rva 0x70000
        public const ulong CMaterialSystem2_DynamicShaderCompile_ProcessQueue = 0x7FFB1127A5E0UL; // rva 0x3A5E0
        public const ulong CMaterialSystem2_DynamicShaderCompile_ReloadAndSync = 0x7FFB112755C1UL; // rva 0x355C2
        public const ulong CMaterialSystem2_DynamicShaderCompile_UnloadAllMaterials = 0x7FFB11279AA0UL; // rva 0x39AA0
        public const ulong CMaterialSystem2_FrameUpdate = 0x7FFB1127BAC0UL; // rva 0x3BAC0
        public const ulong CMaterialSystem2_GetErrorMaterial = 0x7FFB112574D7UL; // rva 0x174D7
        public const ulong CMaterialSystem2_Init = 0x7FFB11276E40UL; // rva 0x36E40
        public const ulong CMaterial_SetVariableAndRenderState = 0x7FFB1126F9B0UL; // rva 0x2F9B0
        public const ulong CVfxProgramData_FindOrCreateStaticComboDataInCache = 0x7FFB112EE0E0UL; // rva 0xAE0E0
        public const ulong CVfxProgramData_FindOrCreateStaticComboData_CacheGate = 0x7FFB112EE950UL; // rva 0xAE950
        public const ulong CVfxProgramData_FindOrLoadStaticComboData = 0x7FFB112FDAE0UL; // rva 0xBDAE0
        public const ulong FindParameter = 0x7FFB11251E30UL; // rva 0x11E30
        public const ulong MatSys__PrepareSceneMaterial = 0x7FFB11251BE0UL; // rva 0x11BE0
        public const ulong UpdateParameter = 0x7FFB11252370UL; // rva 0x12370
    }
    public static class networksystem
    {
        public const ulong CNetChan_ProcessMessages = 0x7FFB0E5AB280UL; // rva 0xBB280
        public const ulong CNetworkSystem_Init = 0x7FFB0E5DC0C0UL; // rva 0xEC0C0
        public const ulong CNetworkSystem_RegisterNetMessageHandlerAbstract = 0x7FFB0E5ABC00UL; // rva 0xBBC00
        public const ulong NetSystem_CNetChan_ProcessMessages = 0x7FFB0E5AB280UL; // rva 0xBB280
        public const ulong NetworkSystem_ptr = 0x7FFB0E776E50UL; // rva 0x286E50
    }
    public static class particles
    {
        public const ulong GetParticleManager = 0x7FFAEC769590UL; // rva 0x579590
        public const ulong Particles__DrawArray = 0x7FFAEC2120B0UL; // rva 0x220B0
        public const ulong Particles__FindKeyVar = 0x7FFAEC22A650UL; // rva 0x3A650
        public const ulong Particles__SetMaterialShaderType = 0x7FFAEC28D8D0UL; // rva 0x9D8D0
    }
    public static class rendersystemdx11
    {
        public const ulong CRenderDeviceBase_CreateConstantBuffer = 0x7FFB11E2F500UL; // rva 0x2F500
        public const ulong CRenderDeviceDx11_BeginSubmittingDisplayLists = 0x7FFB11E3C4E0UL; // rva 0x3C4E0
        public const ulong CRenderDeviceDx11_CompileShaderSourceMain = 0x7FFB11E3FAF0UL; // rva 0x3FAF0
        public const ulong RenderDeviceMgr_ptr = 0x7FFB1222B530UL; // rva 0x42B530
        public const ulong RenderSystemDx11_SetHardwareGammaRamp = 0x7FFB11E3F790UL; // rva 0x3F790
        public const ulong RenderSystemDx11_SetMode = 0x7FFB11E399E0UL; // rva 0x399E0
    }
    public static class resourcesystem
    {
        public const ulong ResourceSystem_BlockingLoadResourceByName = 0x7FFB1E817360UL; // rva 0x17360
        public const ulong ResourceSystem_FindOrRegisterResourceByName = 0x7FFB1E816D80UL; // rva 0x16D80
        public const ulong ResourceSystem_FrameUpdate = 0x7FFB1E81C010UL; // rva 0x1C010
    }
    public static class scenesystem
    {
        public const ulong BuildSceneInfoGpu = 0x7FFAECA54FF0UL; // rva 0x84FF0
        public const ulong CSceneAnimatableObject__GeneratePrimitives = 0x7FFAECA433F0UL; // rva 0x733F0
        public const ulong CSceneAnimatableObject_GeneratePrimitives = 0x7FFAECA433F0UL; // rva 0x733F0
        public const ulong CSceneSkyBoxObject_DrawSkyboxArray = 0x7FFAECB1FA60UL; // rva 0x14FA60
        public const ulong CSceneSystem_CreateStaticShape = 0x7FFAECA819C0UL; // rva 0xB19C0
        public const ulong CSceneSystem_InitGfxObjects = 0x7FFAECA83D00UL; // rva 0xB3D00
        public const ulong CSceneSystem_RenderViewLayer_Dispatch = 0x7FFAECABDC50UL; // rva 0xEDC50
        public const ulong CSceneSystem_Thread_CullView = 0x7FFAECAB91C0UL; // rva 0xE91C0
        public const ulong DrawAggregateSceneObjectArray = 0x7FFAECA0BC00UL; // rva 0x3BC00
        public const ulong DrawObject_legacy = 0x7FFAECA25AC0UL; // rva 0x55AC0
        public const ulong DrawSkyboxArray = 0x7FFAECB1FA60UL; // rva 0x14FA60
        public const ulong SceneSystem__DrawAggeregateObject = 0x7FFAECAFCE20UL; // rva 0x12CE20
        public const ulong SceneSystem__DrawArrayLight = 0x7FFAECA4A990UL; // rva 0x7A990
        public const ulong SceneSystem_Thread_RenderSceneDrawList = 0x7FFAECABD900UL; // rva 0xED900
        public const ulong SceneSystem_ptr = 0x7FFAED2AB490UL; // rva 0x8DB490
    }
    public static class schemasystem
    {
        public const ulong CSchemaSystem_InstallSchemaBindings = 0x7FFB1E7B75D0UL; // rva 0x375D0
        public const ulong CSchemaSystem_RegisterModuleAndBuiltins = 0x7FFB1E7906F0UL; // rva 0x106F0
        public const ulong CSchemaSystem_VerifySchemaBindingConsistency = 0x7FFB1E7858F0UL; // rva 0x58F0
        public const ulong SchemaSystem_ptr = 0x7FFB1E7F6800UL; // rva 0x76800
    }
    public static class soundsystem
    {
        public const ulong CSosOperatorSystem_StartSoundEvent = 0x7FFAEF177AD0UL; // rva 0x1B7AD0
        public const ulong SoundSystem__PlayVSound = 0x7FFAEF309840UL; // rva 0x349840
        public const ulong SoundSystem__SomeUtlSymbolFunc = 0x7FFAEF070740UL; // rva 0xB0740
        public const ulong SoundSystem_ptr = 0x7FFAEF4D2360UL; // rva 0x512360
    }
    public static class tier0
    {
        public const ulong CVar_ptr = 0x7FFB2F0493B0UL; // rva 0x3A93B0
        public const ulong Tier0__LoadKeyValues = 0x7FFB2EDC9160UL; // rva 0x129160
        public const ulong Tier0__UtlBuffer = 0x7FFB2ECF3F10UL; // rva 0x53F10
    }
    public static class vphysics2
    {
        public const ulong VPhysics2_Startup = 0x7FFB0E01AF20UL; // rva 0x6AF20
    }
}
