// Auto-generated by cs2-universal-dumper. Do not edit.
#![allow(non_upper_case_globals, non_snake_case, dead_code)]

pub mod animationsystem {
    /// rva 0x14F0A0
    pub const Animation__ShouldUpdateSequences: usize = 0x7FFAED6EF0A0;
    /// rva 0x812170
    pub const AnimationSystemUtils_ptr: usize = 0x7FFAEDDB2170;
}

pub mod client {
    /// rva 0x78B070
    pub const AddNametagEntity: usize = 0x7FFABF4FB070;
    /// rva 0xA4C790
    pub const AddStattrakEntity: usize = 0x7FFABF7BC790;
    /// rva 0x8AEC70
    pub const AnimGraphRebuild: usize = 0x7FFABF61EC70;
    /// rva 0x7A8A90
    pub const ApplyEconCustomization: usize = 0x7FFABF518A90;
    /// rva 0x8E1EE0
    pub const AutowallInit: usize = 0x7FFABF651EE0;
    /// rva 0x98E9C0
    pub const AutowallTraceData: usize = 0x7FFABF6FE9C0;
    /// rva 0x807780
    pub const AutowallTracePos: usize = 0x7FFABF577780;
    /// rva 0x78E571
    pub const BulkRegenIterator: usize = 0x7FFABF4FE571;
    /// rva 0x31A4FF
    pub const CAM_ThinkReturn: usize = 0x7FFABF08A4FF;
    /// rva 0xEAEC20
    pub const CAttributeStringFill: usize = 0x7FFABFC1EC20;
    /// rva 0x5F86B0
    pub const CAttributeStringInit: usize = 0x7FFABF3686B0;
    /// rva 0x8DB1C0
    pub const CBaseEntity_ChangeModel: usize = 0x7FFABF64B1C0;
    /// rva 0x223D20
    pub const CBaseEntity_TakeDamageOld: usize = 0x7FFABEF93D20;
    /// rva 0x8D9E70
    pub const CBaseModelEntity_SetBodygroup: usize = 0x7FFABF649E70;
    /// rva 0x1BC160
    pub const CBodyComponent: usize = 0x7FFABEF2C160;
    /// rva 0x1C3040
    pub const CBodyComponentSkeletonInstance: usize = 0x7FFABEF33040;
    /// rva 0x17E29D0
    pub const CBufferStringInit: usize = 0x7FFAC05529D0;
    /// rva 0xC5E7F0
    pub const CCSGOInput__CreateMove: usize = 0x7FFABF9CE7F0;
    /// rva 0x7E160
    pub const CCSGameRules: usize = 0x7FFABEDEE160;
    /// rva 0x6E9500
    pub const CCSGameRulesProxy: usize = 0x7FFABF459500;
    /// rva 0x7E5220
    pub const CCSPlayerController: usize = 0x7FFABF555220;
    /// rva 0x7E5220
    pub const CCSPlayerController: usize = 0x7FFABF555220;
    /// rva 0x7E5220
    pub const CCSPlayerController_ActionTrackingServices: usize = 0x7FFABF555220;
    /// rva 0x7E5220
    pub const CCSPlayerController_DamageServices: usize = 0x7FFABF555220;
    /// rva 0x7E5220
    pub const CCSPlayerController_InGameMoneyServices: usize = 0x7FFABF555220;
    /// rva 0x7E5220
    pub const CCSPlayerController_InventoryServices: usize = 0x7FFABF555220;
    /// rva 0x7C3D70
    pub const CCSPlayerInventory__GetItemInLoadout: usize = 0x7FFABF533D70;
    /// rva 0xBB0E40
    pub const CCSPlayerPawn: usize = 0x7FFABF920E40;
    /// rva 0x813BA0
    pub const CCSPlayer_BulletServices: usize = 0x7FFABF583BA0;
    /// rva 0x813BA0
    pub const CCSPlayer_BulletServices: usize = 0x7FFABF583BA0;
    /// rva 0x80FCB0
    pub const CCSPlayer_CameraServices: usize = 0x7FFABF57FCB0;
    /// rva 0x813BA0
    pub const CCSPlayer_HostageServices: usize = 0x7FFABF583BA0;
    /// rva 0x850B00
    pub const CCSPlayer_ItemServices: usize = 0x7FFABF5C0B00;
    /// rva 0x83DE80
    pub const CCSPlayer_MovementServices: usize = 0x7FFABF5ADE80;
    /// rva 0x83DE80
    pub const CCSPlayer_MovementServices: usize = 0x7FFABF5ADE80;
    /// rva 0x850ED0
    pub const CCSPlayer_PingServices: usize = 0x7FFABF5C0ED0;
    /// rva 0x9DBAF0
    pub const CCSPlayer_RunCommand_Context: usize = 0x7FFABF74BAF0;
    /// rva 0x8821D0
    pub const CCSPlayer_UseServices: usize = 0x7FFABF5F21D0;
    /// rva 0x877460
    pub const CCSPlayer_WaterServices: usize = 0x7FFABF5E7460;
    /// rva 0x877810
    pub const CCSPlayer_WeaponServices: usize = 0x7FFABF5E7810;
    /// rva 0x877810
    pub const CCSPlayer_WeaponServices: usize = 0x7FFABF5E7810;
    /// rva 0x77F3D0
    pub const CCSWeaponBase: usize = 0x7FFABF4EF3D0;
    /// rva 0x77F470
    pub const CCSWeaponBaseGun: usize = 0x7FFABF4EF470;
    /// rva 0x75A2B0
    pub const CCSWeaponBaseVData: usize = 0x7FFABF4CA2B0;
    /// rva 0x2E0F90
    pub const CCollisionProperty: usize = 0x7FFABF050F90;
    /// rva 0x13BB8D4
    pub const CCompositeMaterialManager_AddPanoramaPanelRenderRequest_Caller: usize = 0x7FFAC012B8D4;
    /// rva 0x74E1E0
    pub const CDecoyProjectile: usize = 0x7FFABF4BE1E0;
    /// rva 0x104CEA0
    pub const CEconItemSchema__GetAttributeDefinitionByName: usize = 0x7FFABFDBCEA0;
    /// rva 0x10A8A60
    pub const CEconItemView__GetCustomPaintKitIndex: usize = 0x7FFABFE18A60;
    /// rva 0xFE03F0
    pub const CFlashbangProjectile: usize = 0x7FFABFD503F0;
    /// rva 0x27EFD0
    pub const CFogController: usize = 0x7FFABEFEEFD0;
    /// rva 0x1A38F0
    pub const CGameSceneNode: usize = 0x7FFABEF138F0;
    /// rva 0x93FA40
    pub const CGameSceneNode_BuildBoneMergeWork: usize = 0x7FFABF6AFA40;
    /// rva 0x98C5E0
    pub const CGameSceneNode_StartHierarchicalAttachment: usize = 0x7FFABF6FC5E0;
    /// rva 0x98EAA0
    pub const CGameTrace_TraceShape_Client: usize = 0x7FFABF6FEAA0;
    /// rva 0x2E11A0
    pub const CGlowProperty: usize = 0x7FFABF0511A0;
    /// rva 0xB0CD90
    pub const CGlowProperty_OnGlowTypeChanged: usize = 0x7FFABF87CD90;
    /// rva 0xFE0490
    pub const CHEGrenadeProjectile: usize = 0x7FFABFD50490;
    /// rva 0x2064330
    pub const CInputPtrGlobal: usize = 0x7FFAC0DD4330;
    /// rva 0x74E3C0
    pub const CMolotovProjectile: usize = 0x7FFABF4BE3C0;
    /// rva 0x105A690
    pub const CPaintKitDefinitions_FindOrCreateByName: usize = 0x7FFABFDCA690;
    /// rva 0x102C760
    pub const CPaintKitDefinitions_LoadDefaultKit: usize = 0x7FFABFD9C760;
    /// rva 0x2A3D60
    pub const CPostProcessingVolume: usize = 0x7FFABF013D60;
    /// rva 0x13BCA50
    pub const CS2ItemEditor_BuildTemplateMaterialFromFile: usize = 0x7FFAC012CA50;
    /// rva 0x14E8140
    pub const CSBaseGunFireData_fn: usize = 0x7FFAC0258140;
    /// rva 0x2064330
    pub const CSGOInput_ptr: usize = 0x7FFAC0DD4330;
    /// rva 0x2064337
    pub const CSGOInput_resolved: usize = 0x7FFAC0DD4337;
    /// rva 0x1A3A20
    pub const CSkeletonInstance: usize = 0x7FFABEF13A20;
    /// rva 0xA2DB50
    pub const CSkeletonInstance__SetMeshGroupMask: usize = 0x7FFABF79DB50;
    /// rva 0xA1A6C0
    pub const CSkeletonInstance_GetTransformsForHitboxList: usize = 0x7FFABF78A6C0;
    /// rva 0xA25310
    pub const CSkeletonInstance_OnBodyGroupChoiceChanged: usize = 0x7FFABF795310;
    /// rva 0xA264B0
    pub const CSkeletonInstance_PostDataUpdate: usize = 0x7FFABF7964B0;
    /// rva 0xA2C830
    pub const CSkeletonInstance_SetMaterialGroup: usize = 0x7FFABF79C830;
    /// rva 0xA25480
    pub const CSkeletonInstance_SetMeshGroupMask: usize = 0x7FFABF795480;
    /// rva 0x74E460
    pub const CSmokeGrenadeProjectile: usize = 0x7FFABF4BE460;
    /// rva 0x257C90
    pub const CTonemapController2: usize = 0x7FFABEFC7C90;
    /// rva 0x789CA2
    pub const CUtlVector_CompositeMaterialInput_AddToTail: usize = 0x7FFABF4F9C50;
    /// rva 0xC18BB0
    pub const C_AttributeContainer: usize = 0x7FFABF988BB0;
    /// rva 0x4E260
    pub const C_BaseEntity: usize = 0x7FFABEDBE260;
    /// rva 0x158010
    pub const C_BaseModelEntity: usize = 0x7FFABEEC8010;
    /// rva 0x6DA20
    pub const C_BasePlayerPawn: usize = 0x7FFABEDDDA20;
    /// rva 0x9A420
    pub const C_C4: usize = 0x7FFABEE0A420;
    /// rva 0x6C2430
    pub const C_CSPlayerPawn: usize = 0x7FFABF432430;
    /// rva 0xBD7140
    pub const C_CSPlayerPawnBase: usize = 0x7FFABF947140;
    /// rva 0x742170
    pub const C_CSWeaponBase: usize = 0x7FFABF4B2170;
    /// rva 0xBC1460
    pub const C_EconEntity_BuildLegacyGloveSkinMaterial: usize = 0x7FFABF931460;
    /// rva 0x78C2A0
    pub const C_EconEntity_BuildLegacyWeaponSkinMaterial: usize = 0x7FFABF4FC2A0;
    /// rva 0xD84F90
    pub const C_EconEntity_BuildModernWeaponSkinMaterial: usize = 0x7FFABFAF4F90;
    /// rva 0x78B070
    pub const C_EconEntity_BuildNametagOverlayMaterial: usize = 0x7FFABF4FB070;
    /// rva 0x70B570
    pub const C_EconItemView: usize = 0x7FFABF47B570;
    /// rva 0x10B9090
    pub const C_EconWearable_OnNewCustomMaterials: usize = 0x7FFABFE29090;
    /// rva 0xE7480
    pub const C_Hostage: usize = 0x7FFABEE57480;
    /// rva 0xF7440
    pub const C_Inferno: usize = 0x7FFABEE67440;
    /// rva 0xF07A0
    pub const C_PlantedC4: usize = 0x7FFABEE607A0;
    /// rva 0x95A10
    pub const C_SmokeGrenadeProjectile: usize = 0x7FFABEE05A10;
    /// rva 0x207BC0
    pub const CacheParticleEffect: usize = 0x7FFABEF77BC0;
    /// rva 0xC7EBF0
    pub const CalcSpread: usize = 0x7FFABF9EEBF0;
    /// rva 0x7A24F0
    pub const CalcViewmodelTransform_v2: usize = 0x7FFABF5124F0;
    /// rva 0xC6BF20
    pub const CalcViewmodelView: usize = 0x7FFABF9DBF20;
    /// rva 0x14C7E70
    pub const CalculateInterpolation: usize = 0x7FFAC0237E70;
    /// rva 0xDEDDD0
    pub const ClearHUDWeaponIcon: usize = 0x7FFABFB5DDD0;
    /// rva 0xC5C660
    pub const ClientModeCSNormal_OnEvent: usize = 0x7FFABF9CC660;
    /// rva 0x233EAE0
    pub const ClientMode_ptr: usize = 0x7FFAC10AEAE0;
    /// rva 0x14D5B10
    pub const Client_DispatchSpawn: usize = 0x7FFAC0245B10;
    /// rva 0xB91260
    pub const CompositeMaterialPanoramaPanel_Init: usize = 0x7FFABF901260;
    /// rva 0xC7E2D0
    pub const ComputeRandomSeed: usize = 0x7FFABF9EE2D0;
    /// rva 0xACA2B0
    pub const ConCommand_firstperson: usize = 0x7FFABF83A2B0;
    /// rva 0xACA390
    pub const ConCommand_thirdperson: usize = 0x7FFABF83A390;
    /// rva 0x8BF602
    pub const ConvarGet: usize = 0x7FFABF62F602;
    /// rva 0x1510EA0
    pub const CreateBaseTypeCache: usize = 0x7FFAC0280EA0;
    /// rva 0x1604C46
    pub const CreateEntityByClassName: usize = 0x7FFAC0374C46;
    /// rva 0x1835790
    pub const CreateInterface: usize = 0x7FFAC05A5790;
    /// rva 0x4B1D80
    pub const CreateNewSubtickMoveStep: usize = 0x7FFABF221D80;
    /// rva 0x987020
    pub const CreateParticleEffect: usize = 0x7FFABF6F7020;
    /// rva 0xFF7770
    pub const CreateSOSubclassEconItem: usize = 0x7FFABFD67770;
    /// rva 0x81FB40
    pub const DamageFeedbackEmitter: usize = 0x7FFABF58FB40;
    /// rva 0x9463E0
    pub const DestroyParticle: usize = 0x7FFABF6B63E0;
    /// rva 0x35A570
    pub const DispatchEffect: usize = 0x7FFABF0CA570;
    /// rva 0x14D5B10
    pub const DispatchSpawn_caller: usize = 0x7FFAC0245B10;
    /// rva 0x10F0410
    pub const DrawLegs: usize = 0x7FFABFE60410;
    /// rva 0xA66CF0
    pub const DrawOverHead: usize = 0x7FFABF7D6CF0;
    /// rva 0xC7B290
    pub const DrawSmokeVertex: usize = 0x7FFABF9EB290;
    /// rva 0xB63B10
    pub const EmitSoundByHandle: usize = 0x7FFABF8D3B10;
    /// rva 0xC7E380
    pub const FX_FireBullets: usize = 0x7FFABF9EE380;
    /// rva 0xC7E380
    pub const FX_FireBullets: usize = 0x7FFABF9EE380;
    /// rva 0xDC1E98
    pub const FindHudElement: usize = 0x7FFABFB31E98;
    /// rva 0xDC3E70
    pub const FindHudElement_panorama: usize = 0x7FFABFB33E70;
    /// rva 0x181F080
    pub const FindSOCache: usize = 0x7FFAC058F080;
    /// rva 0x10F0410
    pub const FirstPersonLegs: usize = 0x7FFABFE60410;
    /// rva 0xDAB2C0
    pub const FlashOverlay: usize = 0x7FFABFB1B2C0;
    /// rva 0x9D0130
    pub const ForceButtonsDown: usize = 0x7FFABF740130;
    /// rva 0x24D1DF0
    pub const GameEntitySystemPtr: usize = 0x7FFAC1241DF0;
    /// rva 0x939FF0
    pub const GameEventManager_AddListener: usize = 0x7FFABF6A9FF0;
    /// rva 0x992900
    pub const GameEventManager_UnserializeEvent: usize = 0x7FFABF702900;
    /// rva 0x232BFB8
    pub const GameRules_ptr: usize = 0x7FFAC109BFB8;
    /// rva 0x232BFB8
    pub const GetBBox_ptr: usize = 0x7FFAC109BFB8;
    /// rva 0x967600
    pub const GetBaseEntity: usize = 0x7FFABF6D7600;
    /// rva 0x8C81E0
    pub const GetBonePositionByName: usize = 0x7FFABF6381E0;
    /// rva 0x10C3670
    pub const GetChatObject: usize = 0x7FFABFE33670;
    /// rva 0x1036570
    pub const GetClientSystem: usize = 0x7FFABFDA6570;
    /// rva 0x8BDC00
    pub const GetControllerCmd: usize = 0x7FFABF62DC00;
    /// rva 0x379830
    pub const GetEconItemSystem: usize = 0x7FFABF0E9830;
    /// rva 0x967600
    pub const GetEntityByIndex: usize = 0x7FFABF6D7600;
    /// rva 0x94E8D0
    pub const GetEntityHandle: usize = 0x7FFABF6BE8D0;
    /// rva 0xB0ABC0
    pub const GetGlowColor: usize = 0x7FFABF87ABC0;
    /// rva 0xA17C40
    pub const GetHitGroup: usize = 0x7FFABF787C40;
    /// rva 0x22BA670
    pub const GetInstanceS: usize = 0x7FFAC102A670;
    /// rva 0x4AAB40
    pub const GetInt2_Event: usize = 0x7FFABF21AB40;
    /// rva 0x7C6430
    pub const GetInventoryManager: usize = 0x7FFABF536430;
    /// rva 0x8E1070
    pub const GetLocalControllerById: usize = 0x7FFABF651070;
    /// rva 0x8E1070
    pub const GetLocalPawn: usize = 0x7FFABF651070;
    /// rva 0x379200
    pub const GetLocalPlayer_dispatcher: usize = 0x7FFABF0E9200;
    /// rva 0x169C50
    pub const GetMatrixForView: usize = 0x7FFABEED9C50;
    /// rva 0xF00910
    pub const GetPlayerByIndex_export: usize = 0x7FFABFC70910;
    /// rva 0x8B9460
    pub const GetPlayerInterp: usize = 0x7FFABF629460;
    /// rva 0x84D6E0
    pub const GetRemovedAimPunch_E8: usize = 0x7FFABF5BD6E0;
    /// rva 0x112947
    pub const GetRemovedAimpunch: usize = 0x7FFABEE82947;
    /// rva 0x953540
    pub const GetSurfaceData: usize = 0x7FFABF6C3540;
    /// rva 0x8BDA00
    pub const GetTickBase: usize = 0x7FFABF62DA00;
    /// rva 0x806F50
    pub const GetTraceInfo: usize = 0x7FFABF576F50;
    /// rva 0x8BDC90
    pub const GetUserCmdManager: usize = 0x7FFABF62DC90;
    /// rva 0xAD5CA0
    pub const GetViewAngles: usize = 0x7FFABF845CA0;
    /// rva 0x796600
    pub const GetWeaponInAccuracyRecoveryTime: usize = 0x7FFABF506600;
    /// rva 0x80CEF0
    pub const GetWorldFovResolver: usize = 0x7FFABF57CEF0;
    /// rva 0xA8B5A0
    pub const GlobalLightUpdateState: usize = 0x7FFABF7FB5A0;
    /// rva 0x204C5D8
    pub const GlobalVariables_ptr: usize = 0x7FFAC0DBC5D8;
    /// rva 0xBC1460
    pub const GloveApply_PerTick: usize = 0x7FFABF931460;
    /// rva 0x2328DB0
    pub const GlowManager_ptr: usize = 0x7FFAC1098DB0;
    /// rva 0xB0ACD0
    pub const GlowObjectManager_GetInstance: usize = 0x7FFABF87ACD0;
    /// rva 0x8211F0
    pub const HandleBulletPenetration: usize = 0x7FFABF5911F0;
    /// rva 0x1C3700
    pub const HandleEntityList: usize = 0x7FFABEF33700;
    /// rva 0x703EB0
    pub const HandleTeamIntro: usize = 0x7FFABF473EB0;
    /// rva 0x10C10F0
    pub const HudChatPrintf: usize = 0x7FFABFE310F0;
    /// rva 0x13D90B0
    pub const InfoForResourceTypeCCompositeMaterialKit_TypeManager: usize = 0x7FFAC01490B0;
    /// rva 0x13D9600
    pub const InfoForResourceTypeCCompositeMaterial_TypeManager: usize = 0x7FFAC0149600;
    /// rva 0x32BBF0
    pub const InitFilter: usize = 0x7FFABF09BBF0;
    /// rva 0x840660
    pub const InitPlayerMovementTraceFilter: usize = 0x7FFABF5B0660;
    /// rva 0x15FC2A0
    pub const InitTraceInfo: usize = 0x7FFAC036C2A0;
    /// rva 0xB0C300
    pub const IsGlowing: usize = 0x7FFABF87C300;
    /// rva 0x84B0F0
    pub const KillFeedbackEmitter: usize = 0x7FFABF5BB0F0;
    /// rva 0x8D0100
    pub const LevelInit: usize = 0x7FFABF640100;
    /// rva 0x91BF40
    pub const LoadFileForMe: usize = 0x7FFABF68BF40;
    /// rva 0x6BB200
    pub const LoadPath: usize = 0x7FFABF42B200;
    /// rva 0x230B5D0
    pub const LocalPlayerController_ptr: usize = 0x7FFAC107B5D0;
    /// rva 0x8C81E0
    pub const LookupBone: usize = 0x7FFABF6381E0;
    /// rva 0x9DA450
    pub const ModulationUpdate: usize = 0x7FFABF74A450;
    /// rva 0x166C00
    pub const NoClipOnChange: usize = 0x7FFABEED6C00;
    /// rva 0xC7E2D0
    pub const NoSpread1: usize = 0x7FFABF9EE2D0;
    /// rva 0x1F4D90
    pub const ParticleCollection: usize = 0x7FFABEF64D90;
    /// rva 0x20309E8
    pub const ParticleManager_ptr: usize = 0x7FFAC0DA09E8;
    /// rva 0x8D7310
    pub const PhysicsRunThink_Ctrl: usize = 0x7FFABF647310;
    /// rva 0xB0ED50
    pub const PhysicsRunThink_Pawn: usize = 0x7FFABF87ED50;
    /// rva 0x150ED00
    pub const PlayVSound_client: usize = 0x7FFAC027ED00;
    /// rva 0x2057630
    pub const Prediction_ptr: usize = 0x7FFAC0DC7630;
    /// rva 0x9CEA50
    pub const ProcessImpacts: usize = 0x7FFABF73EA50;
    /// rva 0x9D9A30
    pub const ProcessMovement: usize = 0x7FFABF749A30;
    /// rva 0x78C2A0
    pub const RegenerateWeaponSkin: usize = 0x7FFABF4FC2A0;
    /// rva 0x78C2A0
    pub const RegenerateWeaponSkin_v2: usize = 0x7FFABF4FC2A0;
    /// rva 0x7B0D40
    pub const RegenerateWeaponSkins: usize = 0x7FFABF520D40;
    /// rva 0x10ECA50
    pub const RenderDecals: usize = 0x7FFABFE5CA50;
    /// rva 0x602290
    pub const ReportHit: usize = 0x7FFABF372290;
    /// rva 0x9DBAF0
    pub const RunCommand: usize = 0x7FFABF74BAF0;
    /// rva 0x9DBAF0
    pub const RunCommand_processor: usize = 0x7FFABF74BAF0;
    /// rva 0x85D530
    pub const Scope_callsite: usize = 0x7FFABF5CD530;
    /// rva 0x10C10F0
    pub const SendChatMessage: usize = 0x7FFABFE310F0;
    /// rva 0x23298C0
    pub const Sensitivity_ptr: usize = 0x7FFAC10998C0;
    /// rva 0x21EF50
    pub const SetAbsOrigin_Pawn: usize = 0x7FFABEF8EF50;
    /// rva 0xD972A0
    pub const SetBodyGroup_inv: usize = 0x7FFABFB072A0;
    /// rva 0x803980
    pub const SetCollisionBounds: usize = 0x7FFABF573980;
    /// rva 0x1004F60
    pub const SetDynamicAttributeValue: usize = 0x7FFABFD74F60;
    /// rva 0x1004F60
    pub const SetDynamicAttributeValue_raw: usize = 0x7FFABFD74F60;
    /// rva 0xA2DB50
    pub const SetMeshGroupMask: usize = 0x7FFABF79DB50;
    /// rva 0x8DB1C0
    pub const SetModel: usize = 0x7FFABF64B1C0;
    /// rva 0xF1DD90
    pub const SetPlayerReady: usize = 0x7FFABFC8DD90;
    /// rva 0xF1DD90
    pub const SetPlayerReady: usize = 0x7FFABFC8DD90;
    /// rva 0x7D4810
    pub const SetTraceData: usize = 0x7FFABF544810;
    /// rva 0x181AEB0
    pub const SetTypeKV3: usize = 0x7FFAC058AEB0;
    /// rva 0xAE4CE0
    pub const SetViewAngle: usize = 0x7FFABF854CE0;
    /// rva 0x8BAF20
    pub const SetupCmd: usize = 0x7FFABF62AF20;
    /// rva 0xD1D0E0
    pub const SetupMove: usize = 0x7FFABFA8D0E0;
    /// rva 0x1186C8F
    pub const SetupMovementMoves: usize = 0x7FFABFEF6C8F;
    /// rva 0xCA53B0
    pub const ShowMessageBox: usize = 0x7FFABFA153B0;
    /// rva 0xA572B0
    pub const SomeTimingFromPawn: usize = 0x7FFABF7C72B0;
    /// rva 0xBC3FE0
    pub const Spawner_PerTickOrchestrator: usize = 0x7FFABF933FE0;
    /// rva 0x7D92E0
    pub const SpectatorInput: usize = 0x7FFABF5492E0;
    /// rva 0xC7E2D0
    pub const SpreadSeedGen: usize = 0x7FFABF9EE2D0;
    /// rva 0x806E30
    pub const TestSurfaces: usize = 0x7FFABF576E30;
    /// rva 0xACA2B0
    pub const ThirdPersonOffHandler: usize = 0x7FFABF83A2B0;
    /// rva 0xACA390
    pub const ThirdPersonOnHandler: usize = 0x7FFABF83A390;
    /// rva 0x804900
    pub const TraceCreate: usize = 0x7FFABF574900;
    /// rva 0x806F50
    pub const TraceGetInfo: usize = 0x7FFABF576F50;
    /// rva 0x8211F0
    pub const TraceHandleBulletPen: usize = 0x7FFABF5911F0;
    /// rva 0x800580
    pub const TraceInitData: usize = 0x7FFABF570580;
    /// rva 0x32BBF0
    pub const TraceInitFilter: usize = 0x7FFABF09BBF0;
    /// rva 0x15FC2A0
    pub const TraceInitInfo: usize = 0x7FFAC036C2A0;
    /// rva 0xB70E30
    pub const TracePlayerBBox: usize = 0x7FFABF8E0E30;
    /// rva 0x98EAA0
    pub const TraceShape: usize = 0x7FFABF6FEAA0;
    /// rva 0x98EAA0
    pub const TraceShape_Client: usize = 0x7FFABF6FEAA0;
    /// rva 0x804900
    pub const TraceToExit: usize = 0x7FFABF574900;
    /// rva 0xAE4730
    pub const UpdateGlobalVars: usize = 0x7FFABF854730;
    /// rva 0xF21F20
    pub const UpdatePostProcessing: usize = 0x7FFABFC91F20;
    /// rva 0xF21F20
    pub const UpdatePostProcessing: usize = 0x7FFABFC91F20;
    /// rva 0x25A850
    pub const UpdateSkybox: usize = 0x7FFABEFCA850;
    /// rva 0x1FA93B
    pub const UpdateSubClass: usize = 0x7FFABEF6A93B;
    /// rva 0x7AFDA0
    pub const UpdateTurningInAccuracy: usize = 0x7FFABF51FDA0;
    /// rva 0x20306C8
    pub const VPhys2World_ptr: usize = 0x7FFAC0DA06C8;
    /// rva 0x7A0460
    pub const ViewModelHideZoomed: usize = 0x7FFABF510460;
    /// rva 0x2330D38
    pub const ViewRender_ptr: usize = 0x7FFAC10A0D38;
    /// rva 0x22A9D58
    pub const WeaponC4_ptr: usize = 0x7FFAC1019D58;
    /// rva 0xC56330
    pub const WriteSubtickFromEntry: usize = 0x7FFABF9C6330;
    /// rva 0xC7B380
    pub const draw_smoke_array: usize = 0x7FFABF9EB380;
    /// rva 0x8041C0
    pub const draw_view_punch_v2: usize = 0x7FFABF5741C0;
    /// rva 0x24D1EF8
    pub const entity_list_ptr: usize = 0x7FFAC1241EF8;
    /// rva 0xAD2D31
    pub const frame_stage_notify: usize = 0x7FFABF842D31;
    /// rva 0x8041C0
    pub const get_fov: usize = 0x7FFABF5741C0;
    /// rva 0xEDD4F0
    pub const get_map_name: usize = 0x7FFABFC4D4F0;
    /// rva 0xAD4600
    pub const get_view_angles_v2: usize = 0x7FFABF844600;
    /// rva 0x232BFB8
    pub const global_vars_v2: usize = 0x7FFAC109BFB8;
    /// rva 0xEFE9B0
    pub const is_demo_or_hltv: usize = 0x7FFABFC6E9B0;
    /// rva 0xAFA990
    pub const level_init_v2: usize = 0x7FFABF86A990;
    /// rva 0xAFAC10
    pub const level_shutdown: usize = 0x7FFABF86AC10;
    /// rva 0x230B5D0
    pub const local_controller: usize = 0x7FFAC107B5D0;
    /// rva 0x218070
    pub const mark_interp_latch_flags_dirty: usize = 0x7FFABEF88070;
    /// rva 0x968BB0
    pub const on_add_entity_v2: usize = 0x7FFABF6D8BB0;
    /// rva 0xC5F840
    pub const override_view_short: usize = 0x7FFABF9CF840;
    /// rva 0x105D3B0
    pub const paintkit_prefab: usize = 0x7FFABFDCD3B0;
    /// rva 0xEF1330
    pub const paintkit_seed: usize = 0x7FFABFC61330;
    /// rva 0xEF1330
    pub const paintkit_wear: usize = 0x7FFABFC61330;
    /// rva 0x22A9D58
    pub const planted_c4_ptr: usize = 0x7FFAC1019D58;
    /// rva 0x10F0410
    pub const remove_legs: usize = 0x7FFABFE60410;
    /// rva 0xEF1330
    pub const statTrak_killEater: usize = 0x7FFABFC61330;
    /// rva 0x11B7F0
    pub const statTrak_scoreType: usize = 0x7FFABEE8B7F0;
    /// rva 0xAE4730
    pub const update_global_vars: usize = 0x7FFABF854730;
    /// rva 0xF264D6
    pub const update_post_processing_v2: usize = 0x7FFABFC964D6;
    /// rva 0x2331B30
    pub const view_matrix_ptr: usize = 0x7FFAC10A1B30;
}

pub mod engine2 {
    /// rva 0x60CC74
    pub const BuildNumber_addr: usize = 0x7FFB13CDCC74;
    /// rva 0x3FD710
    pub const CCommand_Tokenize: usize = 0x7FFB13ACD710;
    /// rva 0xA1240
    pub const CGameClient_ClientCommand: usize = 0x7FFB13771240;
    /// rva 0x120D70
    pub const CHLTVClient_ExecuteStringCommand: usize = 0x7FFB137F0D70;
    /// rva 0x24A250
    pub const CSplitScreenSlot: usize = 0x7FFB1391A250;
    /// rva 0x3FD270
    pub const Cvar_RegisterConCommand: usize = 0x7FFB13ACD270;
    /// rva 0x3FC080
    pub const Cvar_RegisterConVar: usize = 0x7FFB13ACC080;
    /// rva 0x23D3D2
    pub const DisablePvsAccessor: usize = 0x7FFB1390D3D2;
    /// rva 0x769D0
    pub const Engine__GetScreenAspectRatio: usize = 0x7FFB137469D0;
    /// rva 0x6133F0
    pub const Engine__PVSManager_ptr: usize = 0x7FFB13CE33F0;
    /// rva 0x66490
    pub const Engine__RunPrediction: usize = 0x7FFB13736490;
    /// rva 0x1D1510
    pub const Engine_Disconnect_main: usize = 0x7FFB138A1510;
    /// rva 0x120D70
    pub const Engine_HLTVClient_ExecuteStringCommand: usize = 0x7FFB137F0D70;
    /// rva 0x21AFC0
    pub const Engine_HostStateMgr_QueueNewRequest: usize = 0x7FFB138EAFC0;
    /// rva 0x21AFC0
    pub const Engine_HostStateMgr_QueueNewRequest: usize = 0x7FFB138EAFC0;
    /// rva 0x18D760
    pub const Engine_LoadGameInfo: usize = 0x7FFB1385D760;
    /// rva 0x193440
    pub const Engine_MountAddon: usize = 0x7FFB13863440;
    /// rva 0x69780
    pub const Engine_NetTimeoutDisconnect: usize = 0x7FFB13739780;
    /// rva 0x7F400
    pub const Engine_NetworkGameClient_Connect: usize = 0x7FFB1374F400;
    /// rva 0x60F80
    pub const Engine_NetworkGameClient_SetSignonState: usize = 0x7FFB13730F80;
    /// rva 0x3FD270
    pub const Engine_RegisterConCommand: usize = 0x7FFB13ACD270;
    /// rva 0x3FC080
    pub const Engine_RegisterConVar: usize = 0x7FFB13ACC080;
    /// rva 0x76450
    pub const IsInGame: usize = 0x7FFB13746450;
    /// rva 0x90A0C0
    pub const NetworkGameClient_ptr: usize = 0x7FFB13FDA0C0;
    /// rva 0x90E4EC
    pub const WindowHeight_addr: usize = 0x7FFB13FDE4EC;
    /// rva 0x90E4E8
    pub const WindowWidth_addr: usize = 0x7FFB13FDE4E8;
}

pub mod filesystem_stdio {
    /// rva 0x2157A0
    pub const FullFileSystem_ptr: usize = 0x7FFB136B57A0;
}

pub mod inputsystem {
    /// rva 0x42B50
    pub const InputSystemSvc_ptr: usize = 0x7FFB2B7F2B50;
    /// rva 0x42B50
    pub const InputSystem_ptr: usize = 0x7FFB2B7F2B50;
}

pub mod matchmaking {
    /// rva 0x1B0F80
    pub const GameTypes_ptr: usize = 0x7FFABD560F80;
}

pub mod materialsystem2 {
    /// rva 0x13FA0
    pub const CMaterial2_CompileComboAndGetVariables_DynamicShaderCompile: usize = 0x7FFB11253FA0;
    /// rva 0xBD40
    pub const CMaterial2_GetMode: usize = 0x7FFB1124BD40;
    /// rva 0xC8C0
    pub const CMaterial2_GetVertexShaderInputSignature: usize = 0x7FFB1124C8C0;
    /// rva 0xC8C0
    pub const CMaterial2_GetVertexShaderInputSignature: usize = 0x7FFB1124C8C0;
    /// rva 0x10040
    pub const CMaterial2_LoadShadersAndSetupModes: usize = 0x7FFB11250040;
    /// rva 0x18B80
    pub const CMaterialLayer_ApplyMaterialVarsForBatch: usize = 0x7FFB11258B80;
    /// rva 0x18F80
    pub const CMaterialLayer_BuildPassCommandData: usize = 0x7FFB11258F80;
    /// rva 0x15F3C
    pub const CMaterialLayer_ComputeWorkItemsToSetupStaticCombosForMode: usize = 0x7FFB11255F3C;
    /// rva 0x19820
    pub const CMaterialLayer_CreateCommandBuffer: usize = 0x7FFB11259820;
    /// rva 0x70000
    pub const CMaterialSystem2_BindIdentityInstanceIDBufferAndSetRenderState: usize = 0x7FFB112B0000;
    /// rva 0x3A5E0
    pub const CMaterialSystem2_DynamicShaderCompile_ProcessQueue: usize = 0x7FFB1127A5E0;
    /// rva 0x355C2
    pub const CMaterialSystem2_DynamicShaderCompile_ReloadAndSync: usize = 0x7FFB112755C1;
    /// rva 0x39AA0
    pub const CMaterialSystem2_DynamicShaderCompile_UnloadAllMaterials: usize = 0x7FFB11279AA0;
    /// rva 0x3BAC0
    pub const CMaterialSystem2_FrameUpdate: usize = 0x7FFB1127BAC0;
    /// rva 0x174D7
    pub const CMaterialSystem2_GetErrorMaterial: usize = 0x7FFB112574D7;
    /// rva 0x36E40
    pub const CMaterialSystem2_Init: usize = 0x7FFB11276E40;
    /// rva 0x2F9B0
    pub const CMaterial_SetVariableAndRenderState: usize = 0x7FFB1126F9B0;
    /// rva 0xAE0E0
    pub const CVfxProgramData_FindOrCreateStaticComboDataInCache: usize = 0x7FFB112EE0E0;
    /// rva 0xAE950
    pub const CVfxProgramData_FindOrCreateStaticComboData_CacheGate: usize = 0x7FFB112EE950;
    /// rva 0xBDAE0
    pub const CVfxProgramData_FindOrLoadStaticComboData: usize = 0x7FFB112FDAE0;
    /// rva 0x11E30
    pub const FindParameter: usize = 0x7FFB11251E30;
    /// rva 0x11BE0
    pub const MatSys__PrepareSceneMaterial: usize = 0x7FFB11251BE0;
    /// rva 0x12370
    pub const UpdateParameter: usize = 0x7FFB11252370;
}

pub mod networksystem {
    /// rva 0xBB280
    pub const CNetChan_ProcessMessages: usize = 0x7FFB0E5AB280;
    /// rva 0xEC0C0
    pub const CNetworkSystem_Init: usize = 0x7FFB0E5DC0C0;
    /// rva 0xBBC00
    pub const CNetworkSystem_RegisterNetMessageHandlerAbstract: usize = 0x7FFB0E5ABC00;
    /// rva 0xBB280
    pub const NetSystem_CNetChan_ProcessMessages: usize = 0x7FFB0E5AB280;
    /// rva 0x286E50
    pub const NetworkSystem_ptr: usize = 0x7FFB0E776E50;
}

pub mod particles {
    /// rva 0x579590
    pub const GetParticleManager: usize = 0x7FFAEC769590;
    /// rva 0x220B0
    pub const Particles__DrawArray: usize = 0x7FFAEC2120B0;
    /// rva 0x3A650
    pub const Particles__FindKeyVar: usize = 0x7FFAEC22A650;
    /// rva 0x9D8D0
    pub const Particles__SetMaterialShaderType: usize = 0x7FFAEC28D8D0;
}

pub mod rendersystemdx11 {
    /// rva 0x2F500
    pub const CRenderDeviceBase_CreateConstantBuffer: usize = 0x7FFB11E2F500;
    /// rva 0x3C4E0
    pub const CRenderDeviceDx11_BeginSubmittingDisplayLists: usize = 0x7FFB11E3C4E0;
    /// rva 0x3FAF0
    pub const CRenderDeviceDx11_CompileShaderSourceMain: usize = 0x7FFB11E3FAF0;
    /// rva 0x42B530
    pub const RenderDeviceMgr_ptr: usize = 0x7FFB1222B530;
    /// rva 0x3F790
    pub const RenderSystemDx11_SetHardwareGammaRamp: usize = 0x7FFB11E3F790;
    /// rva 0x399E0
    pub const RenderSystemDx11_SetMode: usize = 0x7FFB11E399E0;
}

pub mod resourcesystem {
    /// rva 0x17360
    pub const ResourceSystem_BlockingLoadResourceByName: usize = 0x7FFB1E817360;
    /// rva 0x16D80
    pub const ResourceSystem_FindOrRegisterResourceByName: usize = 0x7FFB1E816D80;
    /// rva 0x1C010
    pub const ResourceSystem_FrameUpdate: usize = 0x7FFB1E81C010;
}

pub mod scenesystem {
    /// rva 0x84FF0
    pub const BuildSceneInfoGpu: usize = 0x7FFAECA54FF0;
    /// rva 0x733F0
    pub const CSceneAnimatableObject__GeneratePrimitives: usize = 0x7FFAECA433F0;
    /// rva 0x733F0
    pub const CSceneAnimatableObject_GeneratePrimitives: usize = 0x7FFAECA433F0;
    /// rva 0x14FA60
    pub const CSceneSkyBoxObject_DrawSkyboxArray: usize = 0x7FFAECB1FA60;
    /// rva 0xB19C0
    pub const CSceneSystem_CreateStaticShape: usize = 0x7FFAECA819C0;
    /// rva 0xB3D00
    pub const CSceneSystem_InitGfxObjects: usize = 0x7FFAECA83D00;
    /// rva 0xEDC50
    pub const CSceneSystem_RenderViewLayer_Dispatch: usize = 0x7FFAECABDC50;
    /// rva 0xE91C0
    pub const CSceneSystem_Thread_CullView: usize = 0x7FFAECAB91C0;
    /// rva 0x3BC00
    pub const DrawAggregateSceneObjectArray: usize = 0x7FFAECA0BC00;
    /// rva 0x55AC0
    pub const DrawObject_legacy: usize = 0x7FFAECA25AC0;
    /// rva 0x14FA60
    pub const DrawSkyboxArray: usize = 0x7FFAECB1FA60;
    /// rva 0x12CE20
    pub const SceneSystem__DrawAggeregateObject: usize = 0x7FFAECAFCE20;
    /// rva 0x7A990
    pub const SceneSystem__DrawArrayLight: usize = 0x7FFAECA4A990;
    /// rva 0xED900
    pub const SceneSystem_Thread_RenderSceneDrawList: usize = 0x7FFAECABD900;
    /// rva 0x8DB490
    pub const SceneSystem_ptr: usize = 0x7FFAED2AB490;
}

pub mod schemasystem {
    /// rva 0x375D0
    pub const CSchemaSystem_InstallSchemaBindings: usize = 0x7FFB1E7B75D0;
    /// rva 0x106F0
    pub const CSchemaSystem_RegisterModuleAndBuiltins: usize = 0x7FFB1E7906F0;
    /// rva 0x58F0
    pub const CSchemaSystem_VerifySchemaBindingConsistency: usize = 0x7FFB1E7858F0;
    /// rva 0x76800
    pub const SchemaSystem_ptr: usize = 0x7FFB1E7F6800;
}

pub mod soundsystem {
    /// rva 0x1B7AD0
    pub const CSosOperatorSystem_StartSoundEvent: usize = 0x7FFAEF177AD0;
    /// rva 0x349840
    pub const SoundSystem__PlayVSound: usize = 0x7FFAEF309840;
    /// rva 0xB0740
    pub const SoundSystem__SomeUtlSymbolFunc: usize = 0x7FFAEF070740;
    /// rva 0x512360
    pub const SoundSystem_ptr: usize = 0x7FFAEF4D2360;
}

pub mod tier0 {
    /// rva 0x3A93B0
    pub const CVar_ptr: usize = 0x7FFB2F0493B0;
    /// rva 0x129160
    pub const Tier0__LoadKeyValues: usize = 0x7FFB2EDC9160;
    /// rva 0x53F10
    pub const Tier0__UtlBuffer: usize = 0x7FFB2ECF3F10;
}

pub mod vphysics2 {
    /// rva 0x6AF20
    pub const VPhysics2_Startup: usize = 0x7FFB0E01AF20;
}

