//! Entity system accessor generator.
//!
//! Produces `entity_system.hpp` — a header that provides runtime entity
//! traversal helpers by reading the global `CGameEntitySystem` pointer
//! whose RVA is determined by the offsets analysis pass.

use std::fmt::Write;

use crate::analysis::{OffsetMap, SchemaMap};

/// Find a field offset in the schema data, returning a fallback if not found.
fn find_field_offset(schemas: &SchemaMap, module: &str, class: &str, field: &str, fallback: u32) -> u32 {
    if let Some((classes, _)) = schemas.get(module) {
        for c in classes {
            if c.name == class {
                for f in &c.fields {
                    if f.name == field {
                        return f.offset as u32;
                    }
                }
            }
        }
    }
    fallback
}

/// Render the entity system helper header.
pub fn render_hpp(
    offsets: &OffsetMap,
    build_number: Option<u32>,
    schemas: &SchemaMap,
) -> String {
    let mut s = String::new();

    writeln!(s, "// Generated by cs2-sdk — https://cs2-sdk.com").ok();
    writeln!(s, "#pragma once").ok();
    writeln!(s).ok();
    writeln!(s, "#include <cstdint>").ok();
    writeln!(s, "#include <windows.h> // GetModuleHandleA").ok();
    writeln!(s, "#include \"client_dll.hpp\"").ok();
    writeln!(s).ok();

    if let Some(bn) = build_number {
        writeln!(s, "namespace entity {{ inline constexpr std::uint32_t CS2_BUILD = {bn}; }}\n").ok();
    }

    let client_offsets = offsets.get("client.dll").map(|m| m.clone()).unwrap_or_default();
    let dw_game_entity_system = client_offsets.get("dwGameEntitySystem").copied();
    let dw_highest_entity_index = client_offsets.get("dwGameEntitySystem_highestEntityIndex").copied();
    let dw_local_player_controller = client_offsets.get("dwLocalPlayerController").copied();
    let dw_entity_list = client_offsets.get("dwEntityList").copied();

    let entity_system_rva = dw_game_entity_system.or(dw_entity_list).unwrap_or(0);
    let highest_idx_offset = dw_highest_entity_index.unwrap_or(0x2090);
    let local_player_rva = dw_local_player_controller.unwrap_or(0);

    let team_offset = find_field_offset(schemas, "client.dll", "C_BaseEntity", "m_iTeamNum", 0x3EB);
    let pawn_handle_offset = find_field_offset(schemas, "client.dll", "CBasePlayerController", "m_hPawn", 0x6BC);

    writeln!(s, "struct CGameEntitySystem {{").ok();
    writeln!(s, "    /// Get the highest entity index currently in use.").ok();
    writeln!(s, "    static int GetHighestEntityIndex() noexcept {{").ok();
    writeln!(s, "        auto client = reinterpret_cast<uintptr_t>(GetModuleHandleA(\"client.dll\"));").ok();
    writeln!(s, "        if (!client) return 0;").ok();
    writeln!(s, "        auto es = *reinterpret_cast<uintptr_t*>(client + 0x{:X});", entity_system_rva).ok();
    writeln!(s, "        if (!es) return 0;").ok();
    writeln!(s, "        return *reinterpret_cast<int*>(es + 0x{:X});", highest_idx_offset).ok();
    writeln!(s, "    }}").ok();
    writeln!(s).ok();

    writeln!(s, "    /// Get the local player controller using the auto-detected pointer.").ok();
    writeln!(s, "    static client::CCSPlayerController* GetLocalPlayer() noexcept {{").ok();
    writeln!(s, "        auto client = reinterpret_cast<uintptr_t>(GetModuleHandleA(\"client.dll\"));").ok();
    writeln!(s, "        if (!client) return nullptr;").ok();
    writeln!(s, "        return *reinterpret_cast<client::CCSPlayerController**>(client + 0x{:X});", local_player_rva).ok();
    writeln!(s, "    }}").ok();
    writeln!(s).ok();

    writeln!(s, "    /// Walk the chunked entity list and return the CEntityIdentity at index.").ok();
    writeln!(s, "    /// Each chunk holds 512 inline identity structs (0x70 bytes each).").ok();
    writeln!(s, "    static void* GetIdentityByIndex(int index) noexcept {{").ok();
    writeln!(s, "        if (index < 0) return nullptr;").ok();
    writeln!(s, "        auto client = reinterpret_cast<uintptr_t>(GetModuleHandleA(\"client.dll\"));").ok();
    writeln!(s, "        if (!client) return nullptr;").ok();
    writeln!(s, "        auto entity_system = *reinterpret_cast<uintptr_t*>(client + 0x{:X});", entity_system_rva).ok();
    writeln!(s, "        if (!entity_system) return nullptr;").ok();
    writeln!(s, "        // +0x10 is an inline array of 64 chunk pointers (32768 / 512)").ok();
    writeln!(s, "        auto chunk = *reinterpret_cast<uintptr_t*>(entity_system + 0x10 + static_cast<size_t>(index / 512) * 8);").ok();
    writeln!(s, "        if (!chunk) return nullptr;").ok();
    writeln!(s, "        return reinterpret_cast<void*>(chunk + static_cast<size_t>(index % 512) * 0x70);").ok();
    writeln!(s, "    }}").ok();
    writeln!(s).ok();

    writeln!(s, "    /// Get the designer name string for an entity index.").ok();
    writeln!(s, "    static const char* GetDesignerName(int index) noexcept {{").ok();
    writeln!(s, "        auto* identity = GetIdentityByIndex(index);").ok();
    writeln!(s, "        if (!identity) return nullptr;").ok();
    writeln!(s, "        if (!*reinterpret_cast<void**>(identity)) return nullptr;").ok();
    writeln!(s, "        return *reinterpret_cast<const char**>(static_cast<uint8_t*>(identity) + 0x20);").ok();
    writeln!(s, "    }}").ok();
    writeln!(s).ok();

    writeln!(s, "    /// Get the entity pointer at an index by walking the chunked entity list.").ok();
    writeln!(s, "    static void* GetEntityByIndex(int index) noexcept {{").ok();
    writeln!(s, "        if (index < 0 || index >= 32768) return nullptr;").ok();
    writeln!(s, "        auto* identity = GetIdentityByIndex(index);").ok();
    writeln!(s, "        if (!identity) return nullptr;").ok();
    writeln!(s, "        return *reinterpret_cast<void**>(identity);").ok();
    writeln!(s, "    }}").ok();
    writeln!(s).ok();

    writeln!(s, "    /// Check whether a given entity index belongs to a player pawn.").ok();
    writeln!(s, "    /// Iterates controller slots 1-64 and matches the pawn handle.").ok();
    writeln!(s, "    static bool IsPlayerPawn(uint16_t entity_index) noexcept {{").ok();
    writeln!(s, "        for (int i = 1; i <= 64; ++i) {{").ok();
    writeln!(s, "            auto* identity = GetIdentityByIndex(i);").ok();
    writeln!(s, "            if (!identity) continue;").ok();
    writeln!(s, "            auto* controller = *reinterpret_cast<void**>(identity);").ok();
    writeln!(s, "            if (!controller || reinterpret_cast<uintptr_t>(controller) <= 0x10000) continue;").ok();
    writeln!(s, "            auto team = *reinterpret_cast<uint8_t*>(static_cast<uint8_t*>(controller) + 0x{:X});", team_offset).ok();
    writeln!(s, "            if (team != 2 && team != 3) continue;").ok();
            writeln!(s, "            auto& pawn_handle = *reinterpret_cast<CHandle<void>*>(static_cast<uint8_t*>(controller) + 0x{:X});", pawn_handle_offset).ok();
            writeln!(s, "            if (pawn_handle.GetIndex() == entity_index) return true;").ok();
    writeln!(s, "        }}").ok();
    writeln!(s, "        return false;").ok();
    writeln!(s, "    }}").ok();
    writeln!(s).ok();

    writeln!(s, "}}; // struct CGameEntitySystem").ok();
    writeln!(s).ok();

    s
}
