//! Entity-system traversal helpers — an *implementation* header (real code
//! that uses the SDK), kept under `impl/` so it's clearly separated from the
//! pure SDK data (schemas/interfaces/offsets/signatures).
//!
//! Named globals come from the `offsets::` namespace and player fields are read
//! through the typed schema structs, so a re-dump keeps this correct without
//! editing baked-in literals. The only raw constants left are `CEntityIdentity`
//! list-layout details that aren't expressed elsewhere (documented inline).

use std::fmt::Write;

use crate::analysis::{OffsetMap, SchemaMap};

/// Render the entity system helper header (written to `impl/entity_system.hpp`).
pub fn render_hpp(
    _offsets: &OffsetMap,
    build_number: Option<u32>,
    _schemas: &SchemaMap,
) -> String {
    let mut s = String::new();

    writeln!(s, "// Generated by cs2-sdk — https://cs2-sdk.com").ok();
    writeln!(s, "//").ok();
    writeln!(s, "// Implementation helper (uses the SDK) — not pure SDK data.").ok();
    writeln!(s, "#pragma once").ok();
    writeln!(s).ok();
    writeln!(s, "#include <cstdint>").ok();
    writeln!(s, "#include <windows.h> // GetModuleHandleA").ok();
    writeln!(s, "#include \"../offsets.hpp\"").ok();
    writeln!(s, "#include \"../schemas/client_dll.hpp\"").ok();
    writeln!(s).ok();

    if let Some(bn) = build_number {
        writeln!(s, "namespace entity {{ inline constexpr std::uint32_t CS2_BUILD = {bn}; }}\n").ok();
    }

    writeln!(s, "struct CGameEntitySystem {{").ok();
    writeln!(s, "    /// Get the highest entity index currently in use.").ok();
    writeln!(s, "    static int GetHighestEntityIndex() noexcept {{").ok();
    writeln!(s, "        auto client = reinterpret_cast<uintptr_t>(GetModuleHandleA(\"client.dll\"));").ok();
    writeln!(s, "        if (!client) return 0;").ok();
    writeln!(s, "        auto es = *reinterpret_cast<uintptr_t*>(client + offsets::client::GameEntitySystem);").ok();
    writeln!(s, "        if (!es) return 0;").ok();
    writeln!(s, "        return *reinterpret_cast<int*>(es + offsets::client::GameEntitySystem_highestEntityIndex);").ok();
    writeln!(s, "    }}").ok();
    writeln!(s).ok();

    writeln!(s, "    /// Get the local player controller using the auto-detected pointer.").ok();
    writeln!(s, "    static client::CCSPlayerController* GetLocalPlayer() noexcept {{").ok();
    writeln!(s, "        auto client = reinterpret_cast<uintptr_t>(GetModuleHandleA(\"client.dll\"));").ok();
    writeln!(s, "        if (!client) return nullptr;").ok();
    writeln!(s, "        return *reinterpret_cast<client::CCSPlayerController**>(client + offsets::client::LocalPlayerController);").ok();
    writeln!(s, "    }}").ok();
    writeln!(s).ok();

    writeln!(s, "    /// Walk the chunked entity list and return the CEntityIdentity at index.").ok();
    writeln!(s, "    /// Each chunk holds 512 inline identity structs (0x70 bytes each).").ok();
    writeln!(s, "    static void* GetIdentityByIndex(int index) noexcept {{").ok();
    writeln!(s, "        if (index < 0) return nullptr;").ok();
    writeln!(s, "        auto client = reinterpret_cast<uintptr_t>(GetModuleHandleA(\"client.dll\"));").ok();
    writeln!(s, "        if (!client) return nullptr;").ok();
    writeln!(s, "        auto entity_system = *reinterpret_cast<uintptr_t*>(client + offsets::client::GameEntitySystem);").ok();
    writeln!(s, "        if (!entity_system) return nullptr;").ok();
    writeln!(s, "        // CEntityIdentity list layout: +0x10 is an inline array of 64 chunk").ok();
    writeln!(s, "        // pointers (32768 / 512); each chunk is 512 identities of 0x70 bytes.").ok();
    writeln!(s, "        auto chunk = *reinterpret_cast<uintptr_t*>(entity_system + 0x10 + static_cast<size_t>(index / 512) * 8);").ok();
    writeln!(s, "        if (!chunk) return nullptr;").ok();
    writeln!(s, "        return reinterpret_cast<void*>(chunk + static_cast<size_t>(index % 512) * 0x70);").ok();
    writeln!(s, "    }}").ok();
    writeln!(s).ok();

    writeln!(s, "    /// Get the designer name string for an entity index.").ok();
    writeln!(s, "    static const char* GetDesignerName(int index) noexcept {{").ok();
    writeln!(s, "        auto* identity = GetIdentityByIndex(index);").ok();
    writeln!(s, "        if (!identity) return nullptr;").ok();
    writeln!(s, "        if (!*reinterpret_cast<void**>(identity)) return nullptr;").ok();
    writeln!(s, "        // CEntityIdentity::m_designerName lives at +0x20.").ok();
    writeln!(s, "        return *reinterpret_cast<const char**>(static_cast<uint8_t*>(identity) + 0x20);").ok();
    writeln!(s, "    }}").ok();
    writeln!(s).ok();

    writeln!(s, "    /// Get the entity pointer at an index by walking the chunked entity list.").ok();
    writeln!(s, "    static void* GetEntityByIndex(int index) noexcept {{").ok();
    writeln!(s, "        if (index < 0 || index >= 32768) return nullptr;").ok();
    writeln!(s, "        auto* identity = GetIdentityByIndex(index);").ok();
    writeln!(s, "        if (!identity) return nullptr;").ok();
    writeln!(s, "        return *reinterpret_cast<void**>(identity);").ok();
    writeln!(s, "    }}").ok();
    writeln!(s).ok();

    writeln!(s, "    /// Check whether a given entity index belongs to a player pawn.").ok();
    writeln!(s, "    /// Iterates controller slots 1-64 and matches the pawn handle — reads team").ok();
    writeln!(s, "    /// and pawn handle through the typed CCSPlayerController struct.").ok();
    writeln!(s, "    static bool IsPlayerPawn(uint16_t entity_index) noexcept {{").ok();
    writeln!(s, "        for (int i = 1; i <= 64; ++i) {{").ok();
    writeln!(s, "            auto* identity = GetIdentityByIndex(i);").ok();
    writeln!(s, "            if (!identity) continue;").ok();
    writeln!(s, "            auto* controller = reinterpret_cast<client::CCSPlayerController*>(*reinterpret_cast<void**>(identity));").ok();
    writeln!(s, "            if (!controller || reinterpret_cast<uintptr_t>(controller) <= 0x10000) continue;").ok();
    writeln!(s, "            int team = controller->m_iTeamNum();").ok();
    writeln!(s, "            if (team != 2 && team != 3) continue;").ok();
    writeln!(s, "            if (controller->m_hPawn().GetIndex() == entity_index) return true;").ok();
    writeln!(s, "        }}").ok();
    writeln!(s, "        return false;").ok();
    writeln!(s, "    }}").ok();
    writeln!(s).ok();

    writeln!(s, "}}; // struct CGameEntitySystem").ok();
    writeln!(s).ok();

    s
}
