// CS2 SDK — generated by cs2-universal-dumper v1.21.0
// https://github.com/Lucid-cs2/universal-dumper
// 2026-05-05 11:40:23.925081600 UTC

namespace CS2Dumper.Schemas {
    // Module: host.dll
    // Class count: 2
    // Enum count: 0
    public static class HostDll {
        // Parent: None
        // Field count: 1
        public static class EmptyTestScript {
            public const nint m_hTest = 0x10; // CAnimScriptParam<float32>
        }
        // Parent: None
        // Field count: 1
        public static class CAnimScriptBase {
            public const nint m_bIsValid = 0x8; // bool
        }
    }
}
