// CS2 SDK — generated by cs2-universal-dumper v1.21.0
// https://github.com/Lucid-cs2/universal-dumper
// 2026-05-05 11:40:23.925081600 UTC

pub const cs2_dumper = struct {
    pub const schemas = struct {
        // Module: host.dll
        // Class count: 2
        // Enum count: 0
        pub const host_dll = struct {
            // Parent: None
            // Field count: 1
            pub const EmptyTestScript = struct {
                pub const m_hTest: usize = 0x10; // CAnimScriptParam<float32>
            };
            // Parent: None
            // Field count: 1
            pub const CAnimScriptBase = struct {
                pub const m_bIsValid: usize = 0x8; // bool
            };
        };
    };
};
