// CS2 SDK — generated by cs2-universal-dumper v1.21.0
// https://github.com/Lucid-cs2/universal-dumper
// 2026-05-05 11:40:23.925081600 UTC

pub const cs2_dumper = struct {
    pub const schemas = struct {
        // Module: networksystem.dll
        // Class count: 1
        // Enum count: 0
        pub const networksystem_dll = struct {
            // Parent: None
            // Field count: 1
            pub const ChangeAccessorFieldPathIndex_t = struct {
                pub const m_Value: usize = 0x0; // int32
            };
        };
    };
};
