// CS2 SDK — generated by cs2-universal-dumper v1.21.0
// https://github.com/Lucid-cs2/universal-dumper
// 2026-05-05 11:40:23.925081600 UTC

namespace CS2Dumper.Schemas {
    // Module: networksystem.dll
    // Class count: 1
    // Enum count: 0
    public static class NetworksystemDll {
        // Parent: None
        // Field count: 1
        public static class ChangeAccessorFieldPathIndex_t {
            public const nint m_Value = 0x0; // int32
        }
    }
}
