// CS2 SDK — generated by cs2-universal-dumper v1.21.0
// https://github.com/Lucid-cs2/universal-dumper
// 2026-05-05 11:40:23.925081600 UTC

namespace CS2Dumper.Signatures {
    // Module: client.dll
    public static class ClientDll {
        public const nint CreateSOSubclassEconItem = 0xFF7770;
        public const nint GetItemInLoadout = 0x7C3D70;
        public const nint RegenerateWeaponSkin = 0x78C2A0;
        public const nint SetMeshGroupMask = 0xA2DB50;
        public const nint SetModel = 0x8DB1C0;
    }
    // Module: materialsystem2.dll
    public static class Materialsystem2Dll {
        public const nint FindParameter = 0x11E30;
        public const nint PrepareSceneMaterial = 0x11BE0;
        public const nint UpdateParameter = 0x12370;
    }
}
