// CS2 SDK — generated by cs2-universal-dumper v1.21.0
// https://github.com/Lucid-cs2/universal-dumper
// 2026-05-05 11:40:23.925081600 UTC

#pragma once

#include <cstddef>
#include <cstdint>

namespace cs2_dumper {
    namespace signatures {
        // Module: client.dll
        namespace client_dll {
            constexpr std::ptrdiff_t CreateSOSubclassEconItem = 0xFF7770;
            constexpr std::ptrdiff_t GetItemInLoadout = 0x7C3D70;
            constexpr std::ptrdiff_t RegenerateWeaponSkin = 0x78C2A0;
            constexpr std::ptrdiff_t SetMeshGroupMask = 0xA2DB50;
            constexpr std::ptrdiff_t SetModel = 0x8DB1C0;
        }
        // Module: materialsystem2.dll
        namespace materialsystem2_dll {
            constexpr std::ptrdiff_t FindParameter = 0x11E30;
            constexpr std::ptrdiff_t PrepareSceneMaterial = 0x11BE0;
            constexpr std::ptrdiff_t UpdateParameter = 0x12370;
        }
    }
}
