// CS2 SDK — generated by cs2-universal-dumper v1.21.0
// https://github.com/Lucid-cs2/universal-dumper
// 2026-05-05 11:40:23.925081600 UTC

pub const signatures = struct {
    // Module: client.dll
    pub const client_dll = struct {
        pub const CreateSOSubclassEconItem: usize = 0xFF7770;
        pub const GetItemInLoadout: usize = 0x7C3D70;
        pub const RegenerateWeaponSkin: usize = 0x78C2A0;
        pub const SetMeshGroupMask: usize = 0xA2DB50;
        pub const SetModel: usize = 0x8DB1C0;
    };
    // Module: materialsystem2.dll
    pub const materialsystem2_dll = struct {
        pub const FindParameter: usize = 0x11E30;
        pub const PrepareSceneMaterial: usize = 0x11BE0;
        pub const UpdateParameter: usize = 0x12370;
    };
};
