// Generated by cs2-sdk — https://cs2-sdk.com
//
// Implementation helper (uses the SDK) — not pure SDK data.
#pragma once

#include <cstdint>
#include <windows.h> // GetModuleHandleA
#include "../offsets.hpp"
#include "../schemas/client_dll.hpp"

namespace entity { inline constexpr std::uint32_t CS2_BUILD = 14165; }

struct CGameEntitySystem {
    /// Get the highest entity index currently in use.
    static int GetHighestEntityIndex() noexcept {
        auto client = reinterpret_cast<uintptr_t>(GetModuleHandleA("client.dll"));
        if (!client) return 0;
        auto es = *reinterpret_cast<uintptr_t*>(client + offsets::client::GameEntitySystem);
        if (!es) return 0;
        return *reinterpret_cast<int*>(es + offsets::client::GameEntitySystem_highestEntityIndex);
    }

    /// Get the local player controller using the auto-detected pointer.
    static client::CCSPlayerController* GetLocalPlayer() noexcept {
        auto client = reinterpret_cast<uintptr_t>(GetModuleHandleA("client.dll"));
        if (!client) return nullptr;
        return *reinterpret_cast<client::CCSPlayerController**>(client + offsets::client::LocalPlayerController);
    }

    /// Walk the chunked entity list and return the CEntityIdentity at index.
    /// Each chunk holds 512 inline identity structs (0x70 bytes each).
    static void* GetIdentityByIndex(int index) noexcept {
        if (index < 0) return nullptr;
        auto client = reinterpret_cast<uintptr_t>(GetModuleHandleA("client.dll"));
        if (!client) return nullptr;
        auto entity_system = *reinterpret_cast<uintptr_t*>(client + offsets::client::GameEntitySystem);
        if (!entity_system) return nullptr;
        // CEntityIdentity list layout: +0x10 is an inline array of 64 chunk
        // pointers (32768 / 512); each chunk is 512 identities of 0x70 bytes.
        auto chunk = *reinterpret_cast<uintptr_t*>(entity_system + 0x10 + static_cast<size_t>(index / 512) * 8);
        if (!chunk) return nullptr;
        return reinterpret_cast<void*>(chunk + static_cast<size_t>(index % 512) * 0x70);
    }

    /// Get the designer name string for an entity index.
    static const char* GetDesignerName(int index) noexcept {
        auto* identity = GetIdentityByIndex(index);
        if (!identity) return nullptr;
        if (!*reinterpret_cast<void**>(identity)) return nullptr;
        // CEntityIdentity::m_designerName lives at +0x20.
        return *reinterpret_cast<const char**>(static_cast<uint8_t*>(identity) + 0x20);
    }

    /// Get the entity pointer at an index by walking the chunked entity list.
    static void* GetEntityByIndex(int index) noexcept {
        if (index < 0 || index >= 32768) return nullptr;
        auto* identity = GetIdentityByIndex(index);
        if (!identity) return nullptr;
        return *reinterpret_cast<void**>(identity);
    }

    /// Check whether a given entity index belongs to a player pawn.
    /// Iterates controller slots 1-64 and matches the pawn handle — reads team
    /// and pawn handle through the typed CCSPlayerController struct.
    static bool IsPlayerPawn(uint16_t entity_index) noexcept {
        for (int i = 1; i <= 64; ++i) {
            auto* identity = GetIdentityByIndex(i);
            if (!identity) continue;
            auto* controller = reinterpret_cast<client::CCSPlayerController*>(*reinterpret_cast<void**>(identity));
            if (!controller || reinterpret_cast<uintptr_t>(controller) <= 0x10000) continue;
            int team = controller->m_iTeamNum();
            if (team != 2 && team != 3) continue;
            if (controller->m_hPawn().GetIndex() == entity_index) return true;
        }
        return false;
    }

}; // struct CGameEntitySystem

