// Generated by cs2-sdk - https://cs2-sdk.com
//
// Single-include amalgamation header for CS2 internal cheats.
//
// Drop the `sdk/` and `signatures/` folders into your project
// (preserving their relative layout), add `sdk/` to your
// include path, and:
//
//     #include <sdk/cs2.hpp>
//
// gets you typed schema classes, netvars, interface accessors,
// and pattern strings for every resolved signature.

#pragma once

inline constexpr unsigned int CS2_BUILD = 14165;

// SDK macros (SCHEMA_FIELD, field_ref<T>, ...)
#include "cs2sdk_macros.hpp"

// Per-module schema classes
#include "animationsystem_dll.hpp"
#include "engine2_dll.hpp"
#include "host_dll.hpp"
#include "materialsystem2_dll.hpp"
#include "networksystem_dll.hpp"
#include "panorama_dll.hpp"
#include "particles_dll.hpp"
#include "pulse_system_dll.hpp"
#include "rendersystemdx11_dll.hpp"
#include "resourcesystem_dll.hpp"
#include "scenesystem_dll.hpp"
#include "schemasystem_dll.hpp"
#include "client_dll.hpp"
#include "server_dll.hpp"
#include "soundsystem_dll.hpp"
#include "steamaudio_dll.hpp"
#include "vphysics2_dll.hpp"
#include "worldrenderer_dll.hpp"

// Entity system helpers (CGameEntitySystem::GetEntityByIndex, ...)
#include "entity_system.hpp"
// Offsets, interfaces, vtables, buttons, protobufs, signatures
// (netvars.hpp / verified_features.hpp are optional — include
//  them yourself if your project needs them)
#include "offsets.hpp"
#include "interfaces_sdk.hpp"
#include "vtables.hpp"
#include "buttons.hpp"
#include "protobufs.hpp"
#include "../signatures/signatures.hpp"
