// Generated by cs2-sdk — https://cs2-sdk.com
#pragma once

#include <cstdint>
#include <windows.h> // GetModuleHandleA
#include "client_dll.hpp"

namespace entity { inline constexpr std::uint32_t CS2_BUILD = 14165; }

struct CGameEntitySystem {
    /// Get the highest entity index currently in use.
    static int GetHighestEntityIndex() noexcept {
        auto client = reinterpret_cast<uintptr_t>(GetModuleHandleA("client.dll"));
        if (!client) return 0;
        auto es = *reinterpret_cast<uintptr_t*>(client + 0x24E5590);
        if (!es) return 0;
        return *reinterpret_cast<int*>(es + 0x2090);
    }

    /// Get the local player controller using the auto-detected pointer.
    static client::CCSPlayerController* GetLocalPlayer() noexcept {
        auto client = reinterpret_cast<uintptr_t>(GetModuleHandleA("client.dll"));
        if (!client) return nullptr;
        return *reinterpret_cast<client::CCSPlayerController**>(client + 0x231E700);
    }

    /// Walk the chunked entity list and return the CEntityIdentity at index.
    /// Each chunk holds 512 inline identity structs (0x70 bytes each).
    static void* GetIdentityByIndex(int index) noexcept {
        if (index < 0) return nullptr;
        auto client = reinterpret_cast<uintptr_t>(GetModuleHandleA("client.dll"));
        if (!client) return nullptr;
        auto entity_system = *reinterpret_cast<uintptr_t*>(client + 0x24E5590);
        if (!entity_system) return nullptr;
        // +0x10 is an inline array of 64 chunk pointers (32768 / 512)
        auto chunk = *reinterpret_cast<uintptr_t*>(entity_system + 0x10 + static_cast<size_t>(index / 512) * 8);
        if (!chunk) return nullptr;
        return reinterpret_cast<void*>(chunk + static_cast<size_t>(index % 512) * 0x70);
    }

    /// Get the designer name string for an entity index.
    static const char* GetDesignerName(int index) noexcept {
        auto* identity = GetIdentityByIndex(index);
        if (!identity) return nullptr;
        if (!*reinterpret_cast<void**>(identity)) return nullptr;
        return *reinterpret_cast<const char**>(static_cast<uint8_t*>(identity) + 0x20);
    }

    /// Get the entity pointer at an index by walking the chunked entity list.
    static void* GetEntityByIndex(int index) noexcept {
        if (index < 0 || index >= 32768) return nullptr;
        auto* identity = GetIdentityByIndex(index);
        if (!identity) return nullptr;
        return *reinterpret_cast<void**>(identity);
    }

    /// Check whether a given entity index belongs to a player pawn.
    /// Iterates controller slots 1-64 and matches the pawn handle.
    static bool IsPlayerPawn(uint16_t entity_index) noexcept {
        for (int i = 1; i <= 64; ++i) {
            auto* identity = GetIdentityByIndex(i);
            if (!identity) continue;
            auto* controller = *reinterpret_cast<void**>(identity);
            if (!controller || reinterpret_cast<uintptr_t>(controller) <= 0x10000) continue;
            auto team = *reinterpret_cast<uint8_t*>(static_cast<uint8_t*>(controller) + 0x3EB);
            if (team != 2 && team != 3) continue;
            auto& pawn_handle = *reinterpret_cast<CHandle<void>*>(static_cast<uint8_t*>(controller) + 0x6BC);
            if (pawn_handle.GetIndex() == entity_index) return true;
        }
        return false;
    }

}; // struct CGameEntitySystem

