// Generated by cs2-sdk - https://cs2-sdk.com
// Resolved global RVAs, merged from the offset (pattern-scan) and
// Pattern (rip-relative) passes into one tree: offsets::<module>::Name
// (no dw / _ptr affixes).
#pragma once

#include <cstddef>
#include <cstdint>

namespace offsets {
    namespace animationsystem {
        constexpr std::ptrdiff_t AnimationSystemUtils_001 = 0x812190;
        constexpr std::ptrdiff_t AnimationSystem_001 = 0x80A0B0;
        constexpr std::ptrdiff_t pAnimationSystemUtils = 0x812170;
    }
    namespace client {
        constexpr std::ptrdiff_t CInputPtrGlobal = 0x2079860;
        constexpr std::ptrdiff_t CSGOInput = 0x2356240;
        constexpr std::ptrdiff_t ClientToolsInfo_001 = 0x20652C0;
        constexpr std::ptrdiff_t EmptyWorldService001_Client = 0x2028AF0;
        constexpr std::ptrdiff_t EntityList = 0x24E76A0;
        constexpr std::ptrdiff_t GameClientExports001 = 0x2061F60;
        constexpr std::ptrdiff_t GameEntitySystem = 0x24E76A0;
        constexpr std::ptrdiff_t GameEntitySystem_highestEntityIndex = 0x2090;
        constexpr std::ptrdiff_t GameRules = 0x1A02BB8;
        constexpr std::ptrdiff_t GetAbsOrigin = 0x20DF60;
        constexpr std::ptrdiff_t GetBombsiteACenter = 0x84FD70;
        constexpr std::ptrdiff_t GetBombsiteBCenter = 0x84FDD0;
        constexpr std::ptrdiff_t GlobalVars = 0x20616D0;
        constexpr std::ptrdiff_t GlowManager = 0x233DF50;
        constexpr std::ptrdiff_t LegacyGameUI001 = 0x207D480;
        constexpr std::ptrdiff_t LocalPlayerController = 0x2320720;
        constexpr std::ptrdiff_t LocalPlayerPawn = 0x2341698;
        constexpr std::ptrdiff_t ManageGlowSceneObject = 0xADF430;
        constexpr std::ptrdiff_t PlantedC4 = 0x234FF98;
        constexpr std::ptrdiff_t Prediction = 0x23415A0;
        constexpr std::ptrdiff_t Sensitivity = 0x233EA68;
        constexpr std::ptrdiff_t Sensitivity_sensitivity = 0x58;
        constexpr std::ptrdiff_t SetItemItemIdFunction = 0xDA62D0;
        constexpr std::ptrdiff_t SetSceneObjectAttributeFloat4 = 0x174260;
        constexpr std::ptrdiff_t Source2Client002 = 0x233C100;
        constexpr std::ptrdiff_t Source2ClientConfig001 = 0x22ADF80;
        constexpr std::ptrdiff_t Source2ClientPrediction001 = 0x23415A0;
        constexpr std::ptrdiff_t Source2ClientUI001 = 0x207B9E0;
        constexpr std::ptrdiff_t TransformScale3dVMT = 0x1B0C2F0;
        constexpr std::ptrdiff_t TransformTranslate3dVMT = 0x1B03918;
        constexpr std::ptrdiff_t ViewAngles = 0x23568C8;
        constexpr std::ptrdiff_t ViewMatrix = 0x2346B30;
        constexpr std::ptrdiff_t ViewRender = 0x2346EE0;
        constexpr std::ptrdiff_t WeaponC4 = 0x22BED20;
        constexpr std::ptrdiff_t pCSGOInput = 0x2079860;
        constexpr std::ptrdiff_t pClientMode = 0x2353FF0;
        constexpr std::ptrdiff_t pCvar = 0x2558308;
        constexpr std::ptrdiff_t pEntityList = 0x24E76A0;
        constexpr std::ptrdiff_t pEntitySystem = 0x232A490;
        constexpr std::ptrdiff_t pGameEntitySystem = 0x24E76A0;
        constexpr std::ptrdiff_t pGameRules = 0x2341158;
        constexpr std::ptrdiff_t pGameTraceManager = 0x20459A0;
        constexpr std::ptrdiff_t pGetBBox = 0x2341158;
        constexpr std::ptrdiff_t pGlobalVariables = 0x20616D0;
        constexpr std::ptrdiff_t pGlowManager = 0x233DF50;
        constexpr std::ptrdiff_t pHudPanel = 0x23B04D0;
        constexpr std::ptrdiff_t pLocalPlayerController = 0x2320720;
        constexpr std::ptrdiff_t pMainMenuPanel = 0x23A3698;
        constexpr std::ptrdiff_t pParticleManager = 0x2045B48;
        constexpr std::ptrdiff_t pPlantedC4s = 0x234FF90;
        constexpr std::ptrdiff_t pPrediction = 0x23415A0;
        constexpr std::ptrdiff_t pSensitivity = 0x233EA60;
        constexpr std::ptrdiff_t pUiEngine = 0x24FEAF0;
        constexpr std::ptrdiff_t pVPhys2World = 0x20459A0;
        constexpr std::ptrdiff_t pViewMatrix = 0x2346B30;
        constexpr std::ptrdiff_t pViewRender = 0x2346EE0;
        constexpr std::ptrdiff_t pViewToProjectionMatrix = 0x2346AF0;
        constexpr std::ptrdiff_t pWeaponC4 = 0x22BED20;
        constexpr std::ptrdiff_t pWorldToProjectionMatrix = 0x2346B30;
    }
    namespace engine2 {
        constexpr std::ptrdiff_t BenchmarkService001 = 0x6129A0;
        constexpr std::ptrdiff_t BugService001 = 0x8CA9E0;
        constexpr std::ptrdiff_t BuildNumber = 0x60CC74;
        constexpr std::ptrdiff_t ClientServerEngineLoopService_001 = 0x90C0E0;
        constexpr std::ptrdiff_t ClientServerSharedHandleSystem001 = 0x90B690;
        constexpr std::ptrdiff_t EngineGameUI001 = 0x6102A0;
        constexpr std::ptrdiff_t EngineServiceMgr001 = 0x90B9C0;
        constexpr std::ptrdiff_t GameEventSystemClientV001 = 0x90BCA0;
        constexpr std::ptrdiff_t GameEventSystemServerV001 = 0x90BDD0;
        constexpr std::ptrdiff_t GameResourceServiceClientV001 = 0x612AA0;
        constexpr std::ptrdiff_t GameResourceServiceServerV001 = 0x612B00;
        constexpr std::ptrdiff_t GameUIService_001 = 0x8CAE10;
        constexpr std::ptrdiff_t HostStateMgr001 = 0x6132E0;
        constexpr std::ptrdiff_t INETSUPPORT_001 = 0x60C040;
        constexpr std::ptrdiff_t InputService_001 = 0x8CB100;
        constexpr std::ptrdiff_t KeyValueCache001 = 0x613390;
        constexpr std::ptrdiff_t MapListService_001 = 0x909F70;
        constexpr std::ptrdiff_t NetworkClientService_001 = 0x90A100;
        constexpr std::ptrdiff_t NetworkGameClient = 0x90A1A0;
        constexpr std::ptrdiff_t NetworkGameClient_clientTickCount = 0x378;
        constexpr std::ptrdiff_t NetworkGameClient_deltaTick = 0x24C;
        constexpr std::ptrdiff_t NetworkGameClient_isBackgroundMap = 0x2C141F;
        constexpr std::ptrdiff_t NetworkGameClient_localPlayer = 0xF8;
        constexpr std::ptrdiff_t NetworkGameClient_maxClients = 0x240;
        constexpr std::ptrdiff_t NetworkGameClient_serverTickCount = 0x24C;
        constexpr std::ptrdiff_t NetworkGameClient_signOnState = 0x230;
        constexpr std::ptrdiff_t NetworkP2PService_001 = 0x90A440;
        constexpr std::ptrdiff_t NetworkServerService_001 = 0x90A5F0;
        constexpr std::ptrdiff_t NetworkService_001 = 0x612C70;
        constexpr std::ptrdiff_t RenderService_001 = 0x90A860;
        constexpr std::ptrdiff_t ScreenshotService001 = 0x90AB20;
        constexpr std::ptrdiff_t SimpleEngineLoopService_001 = 0x6133F0;
        constexpr std::ptrdiff_t SoundService_001 = 0x612CB0;
        constexpr std::ptrdiff_t Source2EngineToClient001 = 0x60FBA0;
        constexpr std::ptrdiff_t Source2EngineToClientStringTable001 = 0x60FC00;
        constexpr std::ptrdiff_t Source2EngineToServer001 = 0x60FC78;
        constexpr std::ptrdiff_t Source2EngineToServerStringTable001 = 0x60FCA0;
        constexpr std::ptrdiff_t SplitScreenService_001 = 0x612F90;
        constexpr std::ptrdiff_t StatsService_001 = 0x90AEE0;
        constexpr std::ptrdiff_t ToolService_001 = 0x613150;
        constexpr std::ptrdiff_t VENGINE_GAMEUIFUNCS_VERSION005 = 0x610330;
        constexpr std::ptrdiff_t VProfService_001 = 0x613190;
        constexpr std::ptrdiff_t WindowHeight = 0x90E5C4;
        constexpr std::ptrdiff_t WindowWidth = 0x90E5C0;
        constexpr std::ptrdiff_t pBuildNumber = 0x60CC74;
        constexpr std::ptrdiff_t pNetworkGameClient = 0x90A1A0;
        constexpr std::ptrdiff_t pPVSManager = 0x613440;
        constexpr std::ptrdiff_t pWindowHeight = 0x90E5C4;
        constexpr std::ptrdiff_t pWindowWidth = 0x90E5C0;
    }
    namespace filesystem_stdio {
        constexpr std::ptrdiff_t VAsyncFileSystem2_001 = 0x2159E0;
        constexpr std::ptrdiff_t VFileSystem017 = 0x2157A0;
    }
    namespace host {
        constexpr std::ptrdiff_t DebugDrawQueueManager001 = 0x139060;
        constexpr std::ptrdiff_t GameModelInfo001 = 0x1390A0;
        constexpr std::ptrdiff_t GameSystem2HostHook = 0x1390E0;
        constexpr std::ptrdiff_t HostUtils001 = 0x148AB0;
        constexpr std::ptrdiff_t PredictionDiffManager001 = 0x1391F0;
        constexpr std::ptrdiff_t SaveRestoreDataVersion001 = 0x139320;
        constexpr std::ptrdiff_t SinglePlayerSharedMemory001 = 0x139350;
        constexpr std::ptrdiff_t Source2Host001 = 0x1393C0;
    }
    namespace imemanager {
        constexpr std::ptrdiff_t IMEManager001 = 0x36B20;
    }
    namespace inputsystem {
        constexpr std::ptrdiff_t InputStackSystemVersion001 = 0x40E30;
        constexpr std::ptrdiff_t InputSystem = 0x42B50;
        constexpr std::ptrdiff_t InputSystemVersion001 = 0x42B50;
        constexpr std::ptrdiff_t pInputSystem = 0x42B50;
        constexpr std::ptrdiff_t pInputSystemSvc = 0x42B50;
    }
    namespace localize {
        constexpr std::ptrdiff_t Localize_001 = 0x62180;
    }
    namespace matchmaking {
        constexpr std::ptrdiff_t GameTypes = 0x1B0F80;
        constexpr std::ptrdiff_t GameTypes001 = 0x1B0F80;
        constexpr std::ptrdiff_t MATCHFRAMEWORK_001 = 0x1B9060;
    }
    namespace materialsystem2 {
        constexpr std::ptrdiff_t FontManager_001 = 0x15DE60;
        constexpr std::ptrdiff_t MaterialUtils_001 = 0x145D40;
        constexpr std::ptrdiff_t PostProcessingSystem_001 = 0x145C50;
        constexpr std::ptrdiff_t TextLayout_001 = 0x145CD0;
        constexpr std::ptrdiff_t VMaterialSystem2_001 = 0x15D750;
    }
    namespace meshsystem {
        constexpr std::ptrdiff_t MeshSystem001 = 0x150C20;
    }
    namespace navsystem {
        constexpr std::ptrdiff_t NavSystem001 = 0x122930;
    }
    namespace networksystem {
        constexpr std::ptrdiff_t FlattenedSerializersVersion001 = 0x26E750;
        constexpr std::ptrdiff_t NetworkMessagesVersion001 = 0x296A60;
        constexpr std::ptrdiff_t NetworkSystemVersion001 = 0x287EA0;
        constexpr std::ptrdiff_t SerializedEntitiesVersion001 = 0x287F90;
        constexpr std::ptrdiff_t pNetworkSystem = 0x287EA0;
    }
    namespace panorama {
        constexpr std::ptrdiff_t PanoramaUIEngine001 = 0x505D20;
    }
    namespace panorama_text_pango {
        constexpr std::ptrdiff_t PanoramaTextServices001 = 0x2B8A40;
    }
    namespace panoramauiclient {
        constexpr std::ptrdiff_t PanoramaUIClient001 = 0x296420;
    }
    namespace particles {
        constexpr std::ptrdiff_t GetParticleManager = 0x579550;
        constexpr std::ptrdiff_t ParticleSystemMgr003 = 0x54A370;
    }
    namespace pulse_system {
        constexpr std::ptrdiff_t IPulseSystem_001 = 0x1F36A0;
    }
    namespace rendersystemdx11 {
        constexpr std::ptrdiff_t RenderDeviceMgr001 = 0x42B530;
        constexpr std::ptrdiff_t RenderUtils_001 = 0x42BE28;
        constexpr std::ptrdiff_t VRenderDeviceMgrBackdoor001 = 0x42B5D0;
    }
    namespace resourcesystem {
        constexpr std::ptrdiff_t ResourceSystem013 = 0x831E0;
    }
    namespace scenefilecache {
        constexpr std::ptrdiff_t ResponseRulesCache001 = 0xF58F0;
        constexpr std::ptrdiff_t SceneFileCache002 = 0xF5A78;
    }
    namespace scenesystem {
        constexpr std::ptrdiff_t RenderingPipelines_001 = 0x663BA0;
        constexpr std::ptrdiff_t SceneSystem_002 = 0x8DB490;
        constexpr std::ptrdiff_t SceneUtils_001 = 0x664AB0;
        constexpr std::ptrdiff_t pSceneSystem = 0x8DB490;
    }
    namespace schemasystem {
        constexpr std::ptrdiff_t SchemaSystem_001 = 0x76800;
        constexpr std::ptrdiff_t pSchemaSystem = 0x76800;
    }
    namespace server {
        constexpr std::ptrdiff_t EmptyWorldService001_Server = 0x1BF7D40;
        constexpr std::ptrdiff_t EntitySubclassUtilsV001 = 0x1BA3380;
        constexpr std::ptrdiff_t NavGameTest001 = 0x1CA4230;
        constexpr std::ptrdiff_t ServerToolsInfo_001 = 0x1C51238;
        constexpr std::ptrdiff_t Source2GameClients001 = 0x1C4FC90;
        constexpr std::ptrdiff_t Source2GameDirector001 = 0x1DE98E0;
        constexpr std::ptrdiff_t Source2GameEntities001 = 0x1C50940;
        constexpr std::ptrdiff_t Source2Server001 = 0x1C50790;
        constexpr std::ptrdiff_t Source2ServerConfig001 = 0x1F06B68;
        constexpr std::ptrdiff_t customnavsystem001 = 0x1B84668;
    }
    namespace soundsystem {
        constexpr std::ptrdiff_t SoundOpSystem001 = 0x5129B0;
        constexpr std::ptrdiff_t SoundOpSystemEdit001 = 0x512870;
        constexpr std::ptrdiff_t SoundSystem = 0x512360;
        constexpr std::ptrdiff_t SoundSystem001 = 0x512360;
        constexpr std::ptrdiff_t SoundSystem_engineViewData = 0x7C;
        constexpr std::ptrdiff_t VMixEditTool001 = 0x594879F;
        constexpr std::ptrdiff_t pSoundChannels = 0x630040;
        constexpr std::ptrdiff_t pSoundSystem = 0x512360;
    }
    namespace steamaudio {
        constexpr std::ptrdiff_t SteamAudio001 = 0x25E620;
    }
    namespace tier0 {
        constexpr std::ptrdiff_t TestScriptMgr001 = 0x39E6F0;
        constexpr std::ptrdiff_t VEngineCvar007 = 0x3A93B0;
        constexpr std::ptrdiff_t VProcessUtils002 = 0x39E690;
        constexpr std::ptrdiff_t VStringTokenSystem001 = 0x3D00B0;
        constexpr std::ptrdiff_t pCVar = 0x3A93B0;
    }
    namespace v8system {
        constexpr std::ptrdiff_t Source2V8System001 = 0x31730;
    }
    namespace vphysics2 {
        constexpr std::ptrdiff_t VPhysics2_Interface_001 = 0x40DDA0;
    }
    namespace vscript {
        constexpr std::ptrdiff_t VScriptManager010 = 0x13B410;
    }
    namespace worldrenderer {
        constexpr std::ptrdiff_t WorldRendererMgr001 = 0x225C60;
    }
}
