// Generated by cs2-sdk - https://cs2-sdk.com
//
// Single-include amalgamation header for CS2 internal cheats.
//
// Add the dump's `include/` to your include path and:
//
//     #include <cs2.hpp>

#pragma once

inline constexpr unsigned int CS2_BUILD = 14165;

#include "macros.hpp"

// Per-module schema classes
#include "schemas/animationsystem_dll.hpp"
#include "schemas/engine2_dll.hpp"
#include "schemas/host_dll.hpp"
#include "schemas/materialsystem2_dll.hpp"
#include "schemas/networksystem_dll.hpp"
#include "schemas/panorama_dll.hpp"
#include "schemas/particles_dll.hpp"
#include "schemas/pulse_system_dll.hpp"
#include "schemas/rendersystemdx11_dll.hpp"
#include "schemas/resourcesystem_dll.hpp"
#include "schemas/scenesystem_dll.hpp"
#include "schemas/schemasystem_dll.hpp"
#include "schemas/client_dll.hpp"
#include "schemas/server_dll.hpp"
#include "schemas/soundsystem_dll.hpp"
#include "schemas/steamaudio_dll.hpp"
#include "schemas/vphysics2_dll.hpp"
#include "schemas/worldrenderer_dll.hpp"

#include "offsets.hpp"
#include "interfaces.hpp"
#include "interface_classes.hpp"
#include "buttons.hpp"
#include "protobufs.hpp"
#include "signatures.hpp"

// Implementation helpers (use the SDK above) — separated under impl/.
#include "impl/entity_system.hpp"
