// Generated by cs2-sdk - https://cs2-sdk.com
// Resolved global RVAs, merged from the offset (pattern-scan) and
// signature (rip-relative) passes into one tree: offsets::<module>::Name
// (no dw / _ptr affixes).
#pragma once

#include <cstddef>
#include <cstdint>

namespace offsets {
    namespace animationsystem {
        constexpr std::ptrdiff_t AnimationSystemUtils = 0x812170;
    }
    namespace client {
        constexpr std::ptrdiff_t CInputPtrGlobal = 0x2078860;
        constexpr std::ptrdiff_t CSGOInput = 0x2355230;
        constexpr std::ptrdiff_t CSGOInput_resolved = 0x2078867;
        constexpr std::ptrdiff_t ClientMode = 0x2352FE0;
        constexpr std::ptrdiff_t CvarPointer = 0x2557208;
        constexpr std::ptrdiff_t EntityList = 0x24E6590;
        constexpr std::ptrdiff_t EntitySystemPointer = 0x2329490;
        constexpr std::ptrdiff_t GameEntitySystem = 0x24E6590;
        constexpr std::ptrdiff_t GameEntitySystemPtr = 0x24E6590;
        constexpr std::ptrdiff_t GameEntitySystem_highestEntityIndex = 0x2090;
        constexpr std::ptrdiff_t GameRules = 0x1A01BA8;
        constexpr std::ptrdiff_t GameRulesAlt_addr = 0x1A01BA8;
        constexpr std::ptrdiff_t GameRulesPointer = 0x2340158;
        constexpr std::ptrdiff_t GameTraceManager = 0x20449A0;
        constexpr std::ptrdiff_t GetAbsOriginFunction = 0x20DF60;
        constexpr std::ptrdiff_t GetBBox = 0x2340158;
        constexpr std::ptrdiff_t GetBombsiteACenter = 0x84FDC0;
        constexpr std::ptrdiff_t GetBombsiteBCenter = 0x84FE20;
        constexpr std::ptrdiff_t GetInstanceS = 0x22CE7E0;
        constexpr std::ptrdiff_t GlobalVariables = 0x20606D0;
        constexpr std::ptrdiff_t GlobalVars = 0x20606D0;
        constexpr std::ptrdiff_t GlobalVarsPointer = 0x20606D0;
        constexpr std::ptrdiff_t GlowManager = 0x233CF50;
        constexpr std::ptrdiff_t HudPanelPointer = 0x23AF3C0;
        constexpr std::ptrdiff_t ImagePanelConstructorPointer = 0x167D490;
        constexpr std::ptrdiff_t LabelPanelConstructorPointer = 0x164CCA0;
        constexpr std::ptrdiff_t LocalPlayerController = 0x231F700;
        constexpr std::ptrdiff_t LocalPlayerPawn = 0x2340698;
        constexpr std::ptrdiff_t MainMenuPanelPointer = 0x23A2580;
        constexpr std::ptrdiff_t ManageGlowSceneObjectPointer = 0xADF480;
        constexpr std::ptrdiff_t ParticleManager = 0x2044B48;
        constexpr std::ptrdiff_t PlantedC4 = 0x234EF88;
        constexpr std::ptrdiff_t PlantedC4Alt = 0x234EF88;
        constexpr std::ptrdiff_t PlantedC4sPointer = 0x234EF80;
        constexpr std::ptrdiff_t PointerToClientMode = 0x2352FE0;
        constexpr std::ptrdiff_t Prediction = 0x23405A0;
        constexpr std::ptrdiff_t Sensitivity = 0x233DA68;
        constexpr std::ptrdiff_t Sensitivity_sensitivity = 0x58;
        constexpr std::ptrdiff_t SetImageFunctionPointer = 0x1680590;
        constexpr std::ptrdiff_t SetItemItemIdFunction = 0xDA4600;
        constexpr std::ptrdiff_t SetLabelTextFunctionPointer = 0x16580E0;
        constexpr std::ptrdiff_t SetSceneObjectAttributeFloat4 = 0x174260;
        constexpr std::ptrdiff_t SliderSetValueFunction = 0x9E0C20;
        constexpr std::ptrdiff_t TextEntrySetTextFunction = 0x167A4C0;
        constexpr std::ptrdiff_t TransformScale3dVMT = 0x1B0B1F0;
        constexpr std::ptrdiff_t TransformTranslate3dVMT = 0x1B02928;
        constexpr std::ptrdiff_t UiEnginePointer = 0x24FD9F0;
        constexpr std::ptrdiff_t VPhys2World = 0x20449A0;
        constexpr std::ptrdiff_t ViewAngles = 0x23558B8;
        constexpr std::ptrdiff_t ViewMatrix = 0x2345B30;
        constexpr std::ptrdiff_t ViewMatrix_addr = 0x2345B30;
        constexpr std::ptrdiff_t ViewRender = 0x2345ED8;
        constexpr std::ptrdiff_t ViewToProjectionMatrixPointer = 0x2345AF0;
        constexpr std::ptrdiff_t WeaponC4 = 0x22BDD00;
        constexpr std::ptrdiff_t WorldToProjectionMatrixPointer = 0x2345B30;
        constexpr std::ptrdiff_t entity_list = 0x24E6698;
        constexpr std::ptrdiff_t global_vars_v2 = 0x2340158;
        constexpr std::ptrdiff_t local_controller = 0x231F700;
        constexpr std::ptrdiff_t planted_c4 = 0x22BDD00;
        constexpr std::ptrdiff_t view_matrix = 0x2345B30;
    }
    namespace engine2 {
        constexpr std::ptrdiff_t BuildNumber = 0x60CC74;
        constexpr std::ptrdiff_t BuildNumber_addr = 0x60CC74;
        constexpr std::ptrdiff_t NetworkGameClient = 0x90A1A0;
        constexpr std::ptrdiff_t NetworkGameClient_clientTickCount = 0x378;
        constexpr std::ptrdiff_t NetworkGameClient_deltaTick = 0x24C;
        constexpr std::ptrdiff_t NetworkGameClient_isBackgroundMap = 0x2C141F;
        constexpr std::ptrdiff_t NetworkGameClient_localPlayer = 0xF8;
        constexpr std::ptrdiff_t NetworkGameClient_maxClients = 0x240;
        constexpr std::ptrdiff_t NetworkGameClient_serverTickCount = 0x24C;
        constexpr std::ptrdiff_t NetworkGameClient_signOnState = 0x230;
        constexpr std::ptrdiff_t PVSManager = 0x613440;
        constexpr std::ptrdiff_t WindowHeight = 0x90E5C4;
        constexpr std::ptrdiff_t WindowHeight_addr = 0x90E5C4;
        constexpr std::ptrdiff_t WindowWidth = 0x90E5C0;
        constexpr std::ptrdiff_t WindowWidth_addr = 0x90E5C0;
    }
    namespace inputsystem {
        constexpr std::ptrdiff_t InputSystem = 0x42B50;
        constexpr std::ptrdiff_t InputSystemSvc = 0x42B50;
    }
    namespace matchmaking {
        constexpr std::ptrdiff_t GameTypes = 0x1B0F80;
    }
    namespace networksystem {
        constexpr std::ptrdiff_t NetworkSystem = 0x287EA0;
    }
    namespace panorama {
        constexpr std::ptrdiff_t SetPanelStylePropertyFunctionPointer = 0x187C00;
    }
    namespace particles {
        constexpr std::ptrdiff_t GetParticleManager = 0x579550;
    }
    namespace scenesystem {
        constexpr std::ptrdiff_t SceneSystem = 0x8DB490;
        constexpr std::ptrdiff_t SceneSystemPointer = 0x8DB490;
    }
    namespace schemasystem {
        constexpr std::ptrdiff_t SchemaSystem = 0x76800;
    }
    namespace soundsystem {
        constexpr std::ptrdiff_t SoundChannelsPointer = 0x630040;
        constexpr std::ptrdiff_t SoundSystem = 0x512360;
        constexpr std::ptrdiff_t SoundSystem_engineViewData = 0x7C;
    }
    namespace tier0 {
        constexpr std::ptrdiff_t CVar = 0x3A93B0;
    }
}
